window.DAILY_NEWS_DATA = {
  meta: {
    date: "2026-09-28",
    weekday: "星期一",
    title: "广药 游戏开发情报中枢 · 每日技术情报",
    subtitle: "个人学习观察与评述 · 附参考来源外部链接",
    updateTime: "2026-09-28 21:00",
    editor: "广药技术中枢 & CodeBuddy",
    highlights: [
      "《我的世界：地下城2》明日（9/29）发售，首发即入 Game Pass",
      "米哈游刘伟交大演讲：三年最高投入 1000 亿元做 AI 大模型",
      "NVIDIA DLSS 5「3D 引导神经渲染」详解，已在 NBA 2K27 落地",
      "Unity 官方实测：内容目录让增量构建从 32 分钟降到 3 分钟",
      "《Wardogs》首周 220 万份：愿望单转化率 11% 是 3A 均值两倍"
    ],
    engineStatus: [
      { name: "Unity 6.6", type: "unity", status: "9/1正式发布·WebGPU脱离实验版", badge: "推荐生产", color: "indigo" },
      { name: "Unity 7", type: "unity", status: "Unite Seoul公布·12月Beta·2027初发布", badge: "下一代", color: "blue" },
      { name: "团结引擎 1.10.4", type: "tuanjie", status: "9/23发布·持续更新", badge: "国内生态", color: "cyan" },
      { name: "UE 6", type: "unreal", status: "Rocket League首发·2027上线·UEFN合并", badge: "下一代", color: "purple" },
      { name: "Godot 4.8 dev6", type: "godot", status: "9/15发布·月内特性冻结", badge: "开发中", color: "emerald" },
      { name: "Godot 4.7.2", type: "godot", status: "当前稳定版·生产推荐", badge: "LTS", color: "pink" }
    ]
  },
  hero: {
    id: "minecraft-dungeons-ii-launch",
    category: "games",
    categoryName: "热门游戏 · 头条",
    tag: "明日发售",
    title: "《我的世界：地下城2》明日发售：Mojang 相隔六年的续作，Xbox Game Pass 首发即入库",
    summary: "Mojang Studios 动作冒险 RPG《我的世界：地下城2》定档 9 月 29 日发售，登陆 Xbox Series X|S、PC（Xbox Play Anywhere）与 Steam，标准版首发即加入 Game Pass。相隔六年才等来的续作，微软选择用订阅制首日接入来放大首发声量。笔者认为，对想做主机+PC 双端发行的学生团队，这是一份值得研究的平台策略样本。",
    image: "https://cms-assets.xboxservices.com/assets/0f/7f/0f7f4494-633c-439e-97d3-db451b152775.jpg?n=54980885_Sharing-Tile_200x200.jpg",
    source: "Xbox 官网（Mojang Studios / Xbox Game Studios）",
    date: "2026-09-28",
    url: "https://www.xbox.com/en-US/games/minecraft-dungeons-ii",
    readTime: "3 分钟深度",
    hotScore: 90,
    tags: ["Minecraft Dungeons II", "Mojang", "Game Pass", "首发入库", "Xbox Play Anywhere"],
    content: [
      { title: "发售要点", type: "list", items: ["9 月 29 日发售，预购奖励截至 9 月 28 日；", "登陆 Xbox Series X|S / PC / Steam，Xbox Play Anywhere 跨端；", "标准版首发加入 Game Pass；", "掌机体验专门优化；", "豪华版含两枚 DLC 与多款限定外观。"] },
      { title: "笔者观察", type: "text", text: "首日入 Game Pass 是一笔典型的『用短期销量换长期订阅生态』的交易：Mojang 拿到微软流量倾斜，微软拿到首发热度给订阅续费背书。对独立开发者的启示是——首发进订阅制牺牲的是销量曲线，换来的是曝光与社区基数，是否划算取决于你的后续内容更新能力。另外注意 Xbox Play Anywhere：一次购买双端通用，正在成为第一方标配。参考来源：Xbox 官网。" }
    ]
  },
  categories: [
    { id: "all", name: "全部资讯", icon: "🔥", desc: "汇总今日游戏开发全生态情报" },
    { id: "engine", name: "引擎前沿", icon: "🔧", desc: "Unity / 团结引擎 / 虚幻引擎 / Godot / 渲染技术" },
    { id: "industry", name: "行业热点", icon: "📰", desc: "大厂动向 / 财报 / 投融资 / 市场分析" },
    { id: "games", name: "热门游戏", icon: "🎮", desc: "新作发售 / 展会发布 / 热门追踪" },
    { id: "opensource", name: "开源宝库", icon: "⭐", desc: "GitHub 精选开源库 / 工具链 / 引擎框架" },
    { id: "tutorials", name: "实战教程", icon: "📚", desc: "DOTS / C# / 性能优化 / 架构设计" },
    { id: "ai", name: "AI前沿", icon: "🤖", desc: "AI NPC / 智能体 / 生成式AI / 大模型工具" }
  ],
  items: [
    { id: "unity-content-directories", category: "engine", subcategory: "引擎技术", title: "Unity 官方实测：内容目录（Content Directories）让增量构建从 32 分钟降到 3 分钟", summary: "Unity 官方博客详解 Unity 6.6 引入的内容目录——AssetBundle 的高性能细粒度替代方案。Slime Rancher 2 项目实测：增量构建 32 分 16 秒→3 分 4 秒，包体 4GB→2.88GB，且切换后端无需改一行代码。", source: "Unity 官方博客", date: "2026-09-22", url: "https://unity.com/blog/content-directories-beyond-the-assetbundle", image: "", badge: "引擎技术", badgeType: "engine", readTime: "6 分钟", hotScore: 88, tags: ["Unity", "Content Directories", "AssetBundle", "构建优化"], content: [{ title: "技术要点", type: "list", items: ["内容目录是 AssetBundle 的细粒度替代方案，Unity 6.6 可用；", "基于类似 git 的内容寻址存储，用『稳定 ID』引用工件，避免哈希级联变化；", "加载系统完全异步，支持每个工件独立加载/卸载，新增 Loadable<T> 引用类型；", "实测：增量构建 32:16→3:04，Player 包体 4GB→2.88GB，启动到进游戏 45s→30s；", "Unity 7 将把该方案扩展到远程内容传输，按需只下载差异内容。"] }, { title: "笔者观察", type: "text", text: "对被 AssetBundle 布局设计折磨过的团队，这篇相当于官方认错书：『不可分割』的 AB 设计让布局耦合了运行时性能与下载体积二十年。对我们项目最相关的数字是增量构建 10 倍提速——热更迭代效率直接决定调优节奏。Unity 7 的『只下载缺失工件』思路也值得现在的热更架构提前借鉴。参考来源：Unity 官方博客。" }] },
    { id: "unity-simulation-pro-early-access", category: "engine", subcategory: "产品动态", title: "Unity Simulation Pro 开放抢先体验：游戏引擎正在批量吃下机器人仿真市场", summary: "Unity 推出面向机器人仿真的 Simulation Pro 抢先体验版（需 Unity 6.3+ 与 Industry 许可）：URDF 导入、激光雷达/IMU 传感器仿真、ROS 2 兼容、无头 Linux 构建。TIER IV、KITECH、美敦力已有落地案例。", source: "Unity 官方博客", date: "2026-09-22", url: "https://unity.com/blog/unity-simulation-pro-early-access", image: "https://cdn.sanity.io/images/fuvbjjlp/production/51db091ef62d4527f2064d510a146750b02d8786-1915x1045.png", badge: "产品动态", badgeType: "engine", readTime: "5 分钟", hotScore: 76, tags: ["Unity", "Simulation Pro", "机器人仿真", "数字孪生"], content: [{ title: "发布要点", type: "list", items: ["9 月 22 日起开放抢先体验，需 Unity 6.3+ 与 Unity Industry 许可；", "四大能力：URDF 导入器、开箱即用传感器仿真、ROS 2 兼容、无头 Linux 构建；", "KITECH 用点云扫描建铸造厂数字孪生，14 周自动生成 10 万+ 预标注训练帧；", "美敦力为手术机器人建数字孪生，记录全球 195 例手术用于 AI 训练。"] }, { title: "笔者观察", type: "text", text: "游戏引擎的下一个增长曲线不在游戏：合成数据生成、硬件在环测试、数字孪生，全是『仿真』这门老手艺。对学数字媒体的同学，这意味着学引擎的就业面比『进游戏公司』宽得多——自动驾驶、医疗机器人都在招会 Unity 的技术美术和仿真工程师。参考来源：Unity 官方博客。" }] },
    { id: "tuanjie-1-10-4", category: "engine", subcategory: "版本发布", title: "团结引擎 1.10.4 发布：国内生态版本保持双周级迭代", summary: "Unity 中国官网显示团结引擎最新正式版 1.10.4 于 9 月 23 日发布，同期 1.6.13 LTS for HMI（车机版）也于 9 月 11 日更新。国内团队在做引擎选型时，团结的迭代节奏与主机平台支持是关键观察点。", source: "Unity 中国官网（优三缔科技）", date: "2026-09-23", url: "https://unity.cn/tuanjie/releases?u_release_type=full", image: "https://unity-web-prd.cdn.unity.cn/images/logo-new.png", badge: "版本发布", badgeType: "engine", readTime: "2 分钟", hotScore: 70, tags: ["团结引擎", "Unity 中国", "版本更新", "HMI"], content: [{ title: "版本要点", type: "list", items: ["团结引擎最新正式版 1.10.4，2026-09-23 发布；", "车机版 1.6.13 LTS for HMI 于 9/11 更新；", "Windows / macOS / Linux 全平台编辑器可下载；", "详细变更需查看官方 Release Notes。"] }, { title: "笔者观察", type: "text", text: "团结引擎 2.0（7 月发布）之后，1.x 线还在稳定推进小版本，说明国内小游戏、开源鸿蒙、车机三条产品线都进入了常态化维护。对国内学生团队：如果要投微信小游戏，团结引擎的小游戏转换链路是目前最省事的一条路，值得纳入选型对比。参考来源：Unity 中国官网。" }] },
    { id: "nvidia-dlss5-3d-guided", category: "engine", subcategory: "图形渲染", title: "DLSS 5「3D 引导神经渲染」技术拆解：生成式渲染第一次给开发者留了艺术控制权", summary: "NVIDIA 开发者博客详解 DLSS 5 的 3D 引导神经渲染：以引擎渲染帧（含几何、纹理、光照缓冲）为基础叠加细节，一帧进一帧出保证时间稳定，单张 RTX 50 本地跑 4K。NBA 2K27 已上线，同期 ACE 语音模型与 RTX Kit SDK 一并更新。", source: "NVIDIA 技术博客（官方一手来源）", date: "2026-09-22", url: "https://developer.nvidia.com/blog/whats-new-for-game-developers-dlss-5-with-3d-guided-neural-rendering-nvidia-ace-updates-and-new-rtx-kit-capabilities", image: "https://developer-blogs.nvidia.com/wp-content/uploads/2026/09/1_16x9.webp", badge: "图形前沿", badgeType: "engine", readTime: "8 分钟", hotScore: 92, tags: ["DLSS 5", "神经渲染", "NVIDIA ACE", "RTX Kit", "NBA 2K27"], content: [{ title: "技术要点", type: "list", items: ["3D 引导神经渲染：以引擎渲染帧为基础『一帧进一帧出』，确定性输出、时间稳定；", "开发者控制：模型选择、Structure/Tone Intensity 调节、语义 AI 遮罩+引擎级遮罩；", "单张 GeForce RTX 50 本地运行，最高 4K，NBA 2K27 已用于皮肤次表面散射与毛发透射；", "ACE 更新：Nemotron Speech 3.5 流式 ASR（600M）、Qwen3 TTS（600M）、NVIGI SDK 支持 RTX Spark；", "RTX Mega Geometry 2.0 支持高密度网格连续 LOD 集群流式传输，将用于《战争机器：E-Day》。"] }, { title: "笔者观察", type: "text", text: "这条的技术关键是『美术授权的基础不可动摇』——生成式渲染最容易翻车的就是吞掉艺术意图，NVIDIA 用遮罩和强度控制把最终决定权交还开发者，这是生成式技术能进生产管线的前提。对学生项目更有性价比的是 ACE 那部分：600M 级别的语音模型本地就能跑，做 AI NPC 原型不再需要云服务。参考来源：NVIDIA 技术博客。" }] },
    { id: "cgc-software-roundup-0920", category: "engine", subcategory: "工具链", title: "一周 CG 软件更新盘点：Unigine 2.22 加时间轴与动画图，模拟器引擎在悄悄补课", summary: "CG Channel 周报汇总被大新闻淹没的引擎与工具更新：Unigine 2.22 新增 Sequencer 过场动画工具与动画图扩展（IK/Look At/程序化姿势），集成 Cesium 支持行星尺度地理数据，改进高斯泼溅支持。", source: "CG Channel", date: "2026-09-20", url: "https://www.cgchannel.com/2026/09/new-cg-software-you-may-have-missed-20-september-2026/", image: "https://unigine.com//assets/images/opengraph.png", badge: "工具链", badgeType: "engine", readTime: "5 分钟", hotScore: 66, tags: ["Unigine", "CG 工具", "引擎更新", "周报"], content: [{ title: "更新要点", type: "list", items: ["Unigine 2.22：新增 Sequencer 时间轴过场工具，编辑器内直接使用；", "动画图扩展 IK、Look At、关节约束与程序化姿势控制；", "集成 Cesium，支持行星尺度地理空间数据流；实验性重构导航寻路；", "同期工具更新：Animcraft 6.0（AI 角色绑定/蒙皮）、OctaneRender 2026.5（RTX Spark 原生支持）。"] }, { title: "笔者观察", type: "text", text: "Unigine 的路径很值得观察：主战场是仿真和可视化，但它在补齐游戏引擎的『叙事基建』（Sequencer、动画图）——说明即便非游戏客户，也开始要求引擎能做过场与交互叙事。选引擎做非游戏方向（数字孪生、仿真）的同学可以把 Unigine 与 Unity Industry、UE 一起对比。参考来源：CG Channel。" }] },
    { id: "casual-mobile-report-azur", category: "industry", subcategory: "市场数据", title: "休闲手游 Top300 新游只占 2%：下载量与收入彻底脱钩的时代来了", summary: "Azur Games 上半年报告显示：下载量 Top300 中新游占比从 2023 年的 8% 跌到 2%，超一半头部是 2024 年前发布的老产品；超休闲下载跌超 10% 但收入反增 64%，中度游戏收入已超其他品类之和。", source: "GameLook（编译自 Azur Games 报告）", date: "2026-09-28", url: "http://www.gamelook.com.cn/2026/09/603007/", image: "", badge: "市场数据", badgeType: "business", readTime: "6 分钟", hotScore: 84, tags: ["休闲手游", "市场报告", "混合休闲", "长线运营"], content: [{ title: "数据要点", type: "list", items: ["Top300 新游占比：2023 年 8% → 2026 上半年 2%；", "超休闲下载下滑超 10%，收入却增长 64%；混合休闲收入增长 24%；", "中度游戏（Midcore）收入已超过其他所有品类之和；", "eCPM 自 2025 年初持续增长，长线运营可对冲下载下滑；", "方块解谜（Block Puzzle）成为站稳脚跟的新子品类。"] }, { title: "笔者观察", type: "text", text: "报告里最有教学价值的一句话是『决定成败的不是品类标签，而是具体核心玩法及变现逻辑』——三年时间新游占比从 8% 跌到 2%，说明休闲赛道的窗口是『做对一次，吃十年』。对想进大厂做休闲/超休闲的同学，这份报告的潜台词是：买量驱动的增量时代结束了，岗位会越来越偏向长线运营与变现调优。参考来源：GameLook。" }] },
    { id: "japan-market-report-2026", category: "industry", subcategory: "市场数据", title: "日本手游 IAP 年收入仍超 100 亿美元：成熟市场的『下载少、赚得多』生存法则", summary: "Sensor Tower《2026 年日本游戏市场洞察报告》：日本手游 IAP 收入 1.56 万亿日元（超 100 亿美元）虽同比降 5.1%，仍是亚洲第二；《eFootball》借世界杯登顶收入榜；PC/主机半年销量约 2100 万份，动作游戏增 22.4%。", source: "GameLook（编译自 Sensor Tower 报告）", date: "2026-09-23", url: "http://www.gamelook.com.cn/2026/09/602863/", image: "", badge: "市场数据", badgeType: "business", readTime: "6 分钟", hotScore: 78, tags: ["日本市场", "Sensor Tower", "手游收入", "出海"], content: [{ title: "数据要点", type: "list", items: ["日本手游 IAP 收入超 100 亿美元，同比降 5.1%，超韩国 2 倍；", "下载 5.85 亿次（全球第 9），收入排名远高于下载排名=成熟市场特征；", "《eFootball》登顶收入榜，7 月创历史新高；《明日方舟：终末地》《异环》进入增长榜；", "PC/主机 2026 上半年销量约 2100 万份，动作游戏 +22.4%，竞速 +60.1%。"] }, { title: "笔者观察", type: "text", text: "对做出海团队，日本市场的结构信号很清晰：增长不靠新增安装，靠高价值成熟玩家的付费深度——本地化、IP 信任与长线内容节奏的权重高于买量素材。另外注意主机端竞速 +60% 这种异常值，往往意味着档期空缺：品类冷门+大作缺席的窗口期是中小团队可乘之机。参考来源：GameLook。" }] },
    { id: "love-and-deepspace-comeback", category: "industry", subcategory: "产品动态", title: "《恋与深空》重回畅销榜第 2：一款女性向游戏的『危机公关教科书』样本", summary: "9 月 22 日「如若午夜无眠」卡池上线后，《恋与深空》冲回国区 iOS 游戏畅销榜第 2、日本第 4。此前叠纸因「敖尹事件」取消新男主上线、承诺不再新增男主，前期美术与研发投入全部作废——本次回暖证明其基本盘仍在。", source: "GameLook", date: "2026-09-24", url: "http://www.gamelook.com.cn/2026/09/602893/", image: "", badge: "产品动态", badgeType: "business", readTime: "5 分钟", hotScore: 74, tags: ["恋与深空", "叠纸", "女性向", "危机公关"], content: [{ title: "事件要点", type: "list", items: ["「如若午夜无眠」卡池带动游戏重回国区 iOS 游戏畅销榜第 2；", "黎深卡面登上 7 个国家热搜，单人 PV 在 X 平台播放量破 140 万；", "6 月底「敖尹事件」后，叠纸取消第六位男主上线并承诺不再新增；", "月晖商店上架首款支持双向拉链自由互动的服装，展示 3D 布料物理积累。"] }, { title: "笔者观察", type: "text", text: "敖尹事件最贵的教训是『内容方向的决策成本』：一个空降角色的舆论代价直接吞掉建模、剧情、PV、卡面的全部沉没成本。对做内容向产品的同学，启示是社区共识要先于内容排期——尤其是情感型产品，角色阵容本身就是与玩家签的契约。参考来源：GameLook。" }] },
    { id: "gi-hr-summit-2026", category: "industry", subcategory: "行业活动", title: "GamesIndustry.biz HR Summit 10 月 1 日伦敦开幕：AI 进 HR 流程已是明牌议程", summary: "GamesIndustry.biz 公布 HR Summit 2026 完整议程：10 月 1 日伦敦举行，议题覆盖职场神经多样性管理、AI 在人力资源领域的应用、职场文化与工会未来，收尾为 Best Places to Work Awards 颁奖。", source: "GamesIndustry.biz（官方一手来源）", date: "2026-09-25", url: "https://www.gamesindustry.biz/here-is-the-full-line-up-for-the-gamesindustrybiz-hr-summit-2026", image: "https://assetsio.gnwcdn.com/2025_10_02_TRI_JPEG-8-bit-300ppi-(sRGB)-For-Web_00061.jpg?width=1200&height=630&fit=crop&enable=upscale&auto=webp", badge: "行业活动", badgeType: "event", readTime: "3 分钟", hotScore: 64, tags: ["HR Summit", "行业活动", "游戏职场", "AI 招聘"], content: [{ title: "议程要点", type: "list", items: ["10 月 1 日伦敦皇家研究院举行，一天十多场演讲与分会场；", "主题：AI 在 HR 领域的应用、神经多样性管理、职场文化、工会未来；", "演讲方包括 Glowmade CEO、Playstack 高管、HR Confidence Club 创始人等；", "16:00 展望 2027 理想游戏职场，17:15 颁发 Best Places to Work 奖项。"] }, { title: "笔者观察", type: "text", text: "行业峰会把『AI 在雇佣关系中的位置』设为分会场主题，说明 AI 对游戏行业的冲击已经从『怎么做游戏』传导到『怎么招人、怎么留人』。对正在找实习/第一份工作的同学，值得留意 AI 人才战略议题的走向——它大概率决定了未来两年初级岗位的形态。参考来源：GamesIndustry.biz。" }] },
    { id: "jobs-roundup-sept-2026", category: "industry", subcategory: "人事动态", title: "九月游戏业人事盘点：Housemarque 联合创始人 31 年后退休，Massive 迎新任工作室经理", summary: "GamesIndustry.biz 九月人事盘点（9/25 更新）：Natalie Francis 10 月 1 日起任 Massive Entertainment 工作室经理；Housemarque 联合创始人 Ilari Kuittinen 任职 31 年后卸任；Supercell 的 Lasse Seppänen 离职计划 2027 年创业。", source: "GamesIndustry.biz（官方一手来源）", date: "2026-09-25", url: "https://www.gamesindustry.biz/jobs-roundup-september-2026-natalie-francis-appointed-studio-manager-of-massive-entertainment", image: "https://assetsio.gnwcdn.com/massive_managingdirector_nataliefrancis_16x9-1000x563.jpg?width=1200&height=630&fit=crop&enable=upscale&auto=webp", badge: "人事动态", badgeType: "business", readTime: "4 分钟", hotScore: 62, tags: ["人事盘点", "Housemarque", "Massive Entertainment", "行业动向"], content: [{ title: "人事要点", type: "list", items: ["Natalie Francis（前 Avalanche CDO、DICE 运营主管）出任 Massive Entertainment 工作室经理；", "Housemarque 联合创始人 Ilari Kuittinen 31 年后卸任；", "Supercell 的 Lasse Seppänen 离职，计划 2027 年创立新工作室；", "同期变动涉及 Riot、Gearbox、Arrowhead、Tripledot 等约 30 余条任命。"] }, { title: "笔者观察", type: "text", text: "人事盘点是最容易被忽略的『行业健康度指标』：资深创始人批量卸任+高管流向创业，通常意味着新一代工作室的窗口正在打开。关注求职的同学可以把这类盘点当跟踪清单——新工作室的早期招聘往往是进入核心团队的最佳时机。参考来源：GamesIndustry.biz。" }] },
    { id: "graveyard-keeper-2-launch", category: "games", subcategory: "新游发售", title: "《守墓人2》Steam 在线破 5 万：自动化僵尸流水线撑起的模拟经营爆款", summary: "Lazy Bear Games 的中世纪墓地模拟经营续作《守墓人2》9 月末发售，Steam 最高同时在线 54,969 人，好评率 86%，愿望单超 100 万、预购转化率 10%。「尸体转生产资料」的黑色幽默依旧是最大记忆点。", source: "GameLook", date: "2026-09-28", url: "http://www.gamelook.com.cn/2026/09/603006/", image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4358690/000add3ea26cd428656aeb1cff4b030960eb1744/capsule_616x353_alt_assets_1.jpg?t=1790169326", badge: "新游发售", badgeType: "game", readTime: "6 分钟", hotScore: 82, tags: ["守墓人2", "Graveyard Keeper", "模拟经营", "Steam"], content: [{ title: "数据要点", type: "list", items: ["Steam 最高同时在线 54,969 人，好评率 86%（特别好评）；", "愿望单超 100 万，预购转化率 10%；国区定价 68 元；", "玩法升级：取消工具耐久度，新增灵感点系统与传送系统；", "僵尸自动化流水线+僵尸小队战斗构成核心循环。"] }, { title: "笔者观察", type: "text", text: "模拟经营续作能在线破 5 万，靠的不是题材红利而是『把一作核心机制做深』：一代的白骷髅美化是经营，二代把僵尸做成自动化生产链，等于把工厂流水线游戏嫁接进墓地题材。做玩法原型的同学注意它的差评集中在对话文本与肝度——内容量也是模拟经营的隐形门槛。参考来源：GameLook。" }] },
    { id: "lilith-urban-life-sim", category: "games", subcategory: "新作首曝", title: "莉莉丝《奇遇动物城》首曝：生活模拟赛道终于有人把『城市』留下 instead of 删掉", summary: "莉莉丝猫爪拿铁工作室（约 100 人）首曝都市生活模拟新游《奇遇动物城》：现代都市里与小动物室友同居，职业系统从偶像出道到竞选市长，主打生活模拟 GaaS 方向，平台与上线时间待公布。", source: "GameLook", date: "2026-09-28", url: "http://www.gamelook.com.cn/2026/09/602946/", image: "", badge: "新作首曝", badgeType: "game", readTime: "5 分钟", hotScore: 76, tags: ["莉莉丝", "奇遇动物城", "生活模拟", "新作"], content: [{ title: "首曝要点", type: "list", items: ["都市题材差异化：海滨公路、CBD、霓虹商圈里工作、安家、社交；", "小动物是『同居人』而非宠物，有独立作息，还会在游戏内社交 APP 记录玩家日常；", "职业系统对应具体玩法：偶像出道、开奶茶店、竞选市长；", "团队约 100 人，成员来自模拟经营、乙女、二次元领域，制作人理念『不想把城市删掉』。"] }, { title: "笔者观察", type: "text", text: "生活模拟品类这两年被田园、海岛设定卷到同质化，莉莉丝的差异化切口其实很朴素——把场景从『逃离城市』换成『重新设计城市生活』，正好接住都市年轻人的情绪。100 人团队做 GaaS 生活模拟的成本结构不轻，后续看职业系统能不能持续供给内容。参考来源：GameLook。" }] },
    { id: "ace-attorney-dual-destinies-vr", category: "games", subcategory: "新作官宣", title: "《逆转裁判5》VR 版官宣：法庭辩论玩法 2027 年登陆 Quest 与 Meta VR Glasses", summary: "AMATA Games 经 Capcom 官方授权，正式公布《逆转裁判：双六 VR》（Dual Destinies VR），2027 年登陆 Meta Quest 全系与 Meta VR Glasses，支持语音喊出「异议！」与手势指证，含简繁中文字幕。", source: "AMATA K.K. 官方新闻稿（一手来源）", date: "2026-09-24", url: "https://amata.co.jp/en/topics/pressrelease/ace-attorney-vr-20260924.html", image: "https://amata.co.jp/en/wp-content/uploads/2026/09/main_2560x1440_EN-1024x576.png", badge: "新作官宣", badgeType: "game", readTime: "3 分钟", hotScore: 80, tags: ["逆转裁判", "Capcom", "VR", "Meta VR Glasses"], content: [{ title: "官宣要点", type: "list", items: ["AMATA K.K. 获 Capcom 官方授权开发，2027 年发售；", "登陆 Meta Quest 2/3/3S/Pro 与 Meta VR Glasses；", "支持手柄、语音喊「OBJECTION!」与手部追踪手势指证；", "可 3D 立体探索犯罪现场，含简繁中文字幕。"] }, { title: "笔者观察", type: "text", text: "选一部 2013 年的文字冒险做 VR 化，赌的是『法庭对峙的临场感』天然适配沉浸式交互——喊异议、甩证据这些动作本身就有戏剧性。给做 VR 玩法的同学的参考：与其把 3D 场景塞进老玩法，不如找出原玩法里『本来就该用身体完成』的动作做映射。参考来源：AMATA 官方新闻稿。" }] },
    { id: "dressmaker-indie-hit", category: "games", subcategory: "独立爆款", title: "3 人团队《针影裁梦》好评 96%：从 itch.io 三周 Demo 到 Steam 首日畅销第八", summary: "Free Lives 子品牌 Cozy Lives 的 3 人团队裁缝模拟《针影裁梦》9 月 22 日发售：愿望单 6 月破 10 万，首日销量约 2-3 万份、全球畅销第八，同时在线 1.25 万，好评率 96%。起源是主创为患病伴侣做的三周 Demo。", source: "GameLook", date: "2026-09-24", url: "http://www.gamelook.com.cn/2026/09/602908/", image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4019220/dde8e789013d3ff938c10dffa3689e6977b0672c/capsule_616x353.jpg?t=1790484978", badge: "独立爆款", badgeType: "game", readTime: "6 分钟", hotScore: 86, tags: ["针影裁梦", "Dressmaker", "独立游戏", "Free Lives"], content: [{ title: "数据要点", type: "list", items: ["3 人核心团队，发行商 Free Lives 为其孵化 Cozy Lives 子品牌；", "起源：主创为无法做精细缝纫的伴侣 3 周做出 Demo 上架 itch.io，获 15.5 万次下载；", "愿望单 6 月破 10 万；首日销量 2-3 万份、全球畅销榜第八；", "同时在线峰值 1.25 万人，好评率 96%（1455 条评论）。"] }, { title: "笔者观察", type: "text", text: "这是『真实需求驱动设计』的范本：为真实用户（患病的伴侣）解决真实问题，验证成本只有三周和一个 itch.io 页面。玩法设计上它也做了正确的减法——砍掉任务、数值与限时订单，把「自由创作」本身做成核心循环。课程作业想找选题的同学，从身边人的真实爱好里找，比追热点命中率更高。参考来源：GameLook。" }] },
    { id: "aion2-steam-beta", category: "games", subcategory: "测试观察", title: "《永恒之塔2》Steam 测试 7.3 万人在线：韩式 MMO 的商业模式在海外过审有多难", summary: "NCsoft《永恒之塔2》9 月 17 日开启 Steam 全球压力测试，同时在线 7.3 万人，10 月 5 日全球上线。但韩服「免费绝不 P2W」的口碑崩塌前科被海外玩家翻出，会员订阅锁拍卖行等设计成为最大争议点。", source: "GameLook", date: "2026-09-24", url: "http://www.gamelook.com.cn/2026/09/602892/", image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3393110/aac8c918571c7e5a82e8e8345126853d1470b68a/capsule_616x353.jpg?t=1789780043", badge: "测试观察", badgeType: "game", readTime: "6 分钟", hotScore: 78, tags: ["永恒之塔2", "NCsoft", "MMO", "商业模式"], content: [{ title: "事件要点", type: "list", items: ["9/17 Steam 全球压测，同时在线 7.3 万人；10/5 全球上线；", "韩服曾创 DAU 超 150 万、两月营收千亿韩元，但开服 15 小时即道歉；", "争议核心：宣称免费无 P2W，实际售卖战斗强化道具、会员锁拍卖行等核心功能；", "美术争议：Reddit 女玩家集中吐槽男女角色服饰差异过大。"] }, { title: "笔者观察", type: "text", text: "7.3 万在线说明 IP 号召力仍在，但海外玩家已经学会在测试期就审查商业化条款——『先道歉后改』的韩服剧本第二次演就不管用了。对比《燕云十六声》只卖外观在海外的好评，定价诚信正在从加分项变成及格线。做商业化的同学把这个案例存档。参考来源：GameLook。" }] },
    { id: "stride-4-4-0-beta8", category: "opensource", subcategory: "引擎发布", title: "Stride 4.4.0-beta8 发布：C# 开源引擎集中修 Vulkan 同步与 Shader 编译", summary: "开源 C# 引擎 Stride 连发版本推进 4.4.0：beta8（9/21）修复 Vulkan GPU 同步、体素 GI 与线框渲染等多个 shader 编译错误，新项目改为后台下载示例内容；beta7 起支持游戏项目面向 .NET 11 运行。", source: "GitHub: stride3d/stride（官方一手来源）", date: "2026-09-21", url: "https://github.com/stride3d/stride/releases/tag/releases/4.4.0-beta8", image: "https://repository-images.githubusercontent.com/136570231/101bce80-9e79-11e9-8b47-ad976e64e5f3", badge: "版本发布", badgeType: "engine", readTime: "4 分钟", hotScore: 68, tags: ["Stride", "开源引擎", "C#", "Vulkan"], content: [{ title: "版本要点", type: "list", items: ["beta8（9/21）：修复 Vulkan 渲染目标/深度缓冲读取、compute shader 等 GPU 同步问题；", "修复常量标签、数组尺寸、体素 GI、线框渲染等 shader 编译错误；", "beta7（9/16）：支持项目面向比引擎自带版本更新的 .NET（如 .NET 11）；", "样例/模板/资产包改为独立版本发布，修复可更快到达用户。"] }, { title: "笔者观察", type: "text", text: "Stride 这波迭代里最值得学的是『内容包与引擎版本解耦』——样例和资产独立发版，让修复不用等引擎大版本，这对所有做引擎/工具链的团队都是通用的工程决策。C# 全栈（编辑器+运行时）的架构也让它成为想读引擎源码的 C# 学习者的好教材。参考来源：GitHub。" }] },
    { id: "defold-1-14-0-alpha", category: "opensource", subcategory: "引擎发布", title: "Defold 1.14.0 进入 Alpha：轻量引擎的三通道发布节奏值得关注", summary: "Defold 于 9 月 10 日同日发布 1.14.0-alpha 与 1.13.2-beta，alpha→beta→stable 三通道模式让开发者可按风险偏好选择跟进节奏；当前稳定版为 1.13.1（8/17），引擎以极小 Web 构建体积见长。", source: "GitHub: defold/defold（官方一手来源）", date: "2026-09-10", url: "https://github.com/defold/defold/releases/tag/1.14.0-alpha", image: "https://repository-images.githubusercontent.com/4315538/d4ff8c80-99b1-11ea-9c09-b2167399b0b6", badge: "版本发布", badgeType: "engine", readTime: "3 分钟", hotScore: 62, tags: ["Defold", "开源引擎", "小游戏", "发布工程"], content: [{ title: "版本要点", type: "list", items: ["1.14.0-alpha 与 1.13.2-beta 于 9/10 同日发布；", "当前稳定版 1.13.1（8/17），提供 17 个平台构建产物；", "Defold 为 Defold 基金会所有的 source-available 引擎，主打桌面/移动/网页；", "上半年路线重点：更小 Web 构建体积、更强 3D、更深物理脚本。"] }, { title: "笔者观察", type: "text", text: "Defold 的 alpha→beta→stable 三通道+每日构建，是小型引擎团队可以照抄的发布工程模板：用户分层消化风险，CI 压力可控。做小游戏选型的同学，Defold 的 Web 端包体优势依然明显，适合轻量休闲品类。参考来源：GitHub。" }] },
    { id: "supersplat-editor-3-0", category: "opensource", subcategory: "工具发布", title: "SuperSplat Editor 3.0 全面重写：440 万高斯泼溅场景内存从 1.5GB 降到 105MB", summary: "PlayCanvas 开源的 3DGS 编辑器 SuperSplat 3.0 基于 WebGPU Compute 从零重写：投影/剔除/排序全部上 GPU，440 万 splat 场景空闲内存从 1557MB 降至 105MB，新增免排序随机不透明渲染与球形笔刷选择。", source: "PlayCanvas 官方博客（MIT 开源项目）", date: "2026-09-09", url: "https://blog.playcanvas.com/new-in-supersplat-editor-3-0-rebuilt-on-webgpu", image: "https://repository-images.githubusercontent.com/707265118/f42dba0a-ced5-43fb-8579-a8e8c6c39b19", badge: "工具发布", badgeType: "engine", readTime: "7 分钟", hotScore: 74, tags: ["SuperSplat", "3DGS", "WebGPU", "PlayCanvas"], content: [{ title: "版本要点", type: "list", items: ["渲染器与数据模型从零重写，仅支持 WebGPU（Chrome/Edge、Safari 26+）；", "440 万 splat 场景：JS 堆内存 1557MB→105MB，降幅约 93%；", "Stochastic Alpha 免排序渲染让 2000 万高斯场景保持交互流畅；", "球形笔刷直接在 3D 表面绘制选择；Orient 工具从 8.5 秒提速到 25 毫秒。"] }, { title: "笔者观察", type: "text", text: "这是 WebGPU Compute 改造生产力工具的标杆案例：把投影、排序这类『看起来必须 CPU 干』的活全部搬上 GPU，换来一个数量级的内存与交互改善。做三维扫描/实景复刻内容的团队，SuperSplat 可以直接进管线（网页端免费、MIT 开源）。参考来源：PlayCanvas 官方博客。" }] },
    { id: "armorpaint-1-0", category: "opensource", subcategory: "工具发布", title: "ArmorPaint 1.0 正式发布：纯 C 重写的开源 PBR 绘制软件，代码能装进两张软盘", summary: "开发七年的开源节点式 3D 纹理绘制软件 ArmorPaint 发布 1.0：整体用 C 语言重写、零外部依赖，支持 D3D12/Vulkan/Metal/WebGPU 与各平台光线追踪，新增网格修改器、UV 编辑器与完全本地运行的 Neural Nodes 生成式 AI 功能。", source: "80.lv（报道开源项目 ArmorPaint）", date: "2026-09-07", url: "https://80.lv/articles/open-source-substance-3d-painter-alternative-armorpaint-1-0-released", image: "https://cdn.80.lv/api/upload/meta/50083/images/6a9eea1ec6130/contain_1200x630.jpg", badge: "工具发布", badgeType: "engine", readTime: "5 分钟", hotScore: 70, tags: ["ArmorPaint", "开源", "PBR", "纹理绘制"], content: [{ title: "版本要点", type: "list", items: ["从 Haxe+V8 整体重写为纯 C，无外部依赖库，代码库可装进两张 1.44MB 软盘；", "支持 D3D12 / Vulkan / Metal / WebGPU 四套图形后端与平台光追；", "新增 Decimate/Smooth/Bevel/Subdivide 网格修改器与基础 UV 编辑器；", "Neural Nodes：生成式 AI 节点，官方称完全在本地设备运行。"] }, { title: "笔者观察", type: "text", text: "『纯 C 重写+零依赖』在 2026 年是个逆潮流但正确的技术赌注：启动速度、内存占用、跨平台打包成本全被压到极低，学生笔记本也能流畅跑。对学图形的同学，这套自研 3D 引擎+2D 绘图+UI 的代码库是读源码的优质样本。参考来源：80.lv。" }] },
    { id: "bevy-0-20-rc1", category: "opensource", subcategory: "引擎发布", title: "Bevy 0.20 进入 RC 阶段：Rust ECS 引擎的半年一个大版本节奏稳定运转", summary: "Rust 游戏引擎 Bevy 于 9 月 15 日发布 v0.20.0-rc.1，正式版临近；当前稳定版为 8/13 的 v0.19.1。Bevy 坚持『半年一个大版本+RC 兜底』的发布节奏，仓库 star 数已达 48.4k。", source: "GitHub: bevyengine/bevy（官方一手来源）", date: "2026-09-15", url: "https://github.com/bevyengine/bevy/releases/tag/v0.20.0-rc.1", image: "https://repository-images.githubusercontent.com/234798675/18016580-dab2-11ea-9864-452f7149499c", badge: "版本发布", badgeType: "engine", readTime: "3 分钟", hotScore: 66, tags: ["Bevy", "Rust", "ECS", "开源引擎"], content: [{ title: "版本要点", type: "list", items: ["v0.20.0-rc.1 于 9/15 发布，完整变更可对比 v0.19.1...v0.20.0-rc.1；", "当前最新稳定版 v0.19.1（8/13）；", "Bevy 发布惯例：多个 RC 预发布后推正式版；", "社区反响热烈：该 RC 收到 53 人共 97 个表情反应。"] }, { title: "笔者观察", type: "text", text: "Bevy 的价值不只是引擎本身，还有它对『开源项目怎么管理破坏性变更』的示范：半年大版本+RC 窗口+迁移指南，让生态跟得上而不过度保守。想学 Rust 或 ECS 架构的同学，从 Bevy 的迁移文档入手比啃理论更高效。参考来源：GitHub。" }] },
    { id: "rust-ltd-h3vr2-gun-sim", category: "tutorials", subcategory: "开发复盘", title: "RUST LTD 官方复盘：VR 枪械仿真为什么必须『自研物理+PhysX』双轨并行", summary: "Unity 官方博客专访 H3VR2 团队：枪械内部组件用自研模拟系统（独立于游戏物理引擎），游戏空间用 PhysX，弹道与爆炸用 ECS+Burst；立项前花近 6 个月只做架构与工具，团队从 1 人扩到 20+ 人。", source: "Unity 官方博客（一手专访）", date: "2026-09-25", url: "https://unity.com/blog/rust-ltd-hot-dogs-horseshoes-hand-grenades-2", image: "https://cdn.sanity.io/images/fuvbjjlp/production/d3f66cb2ead49fa214d98575fe8ebc085533d084-3840x2160.png", badge: "开发复盘", badgeType: "game", readTime: "8 分钟", hotScore: 84, tags: ["H3VR2", "VR", "物理仿真", "ECS"], content: [{ title: "复盘要点", type: "list", items: ["进内容制作前花近 6 个月专注架构与工具开发；", "枪械内部组件自研模拟（弹簧常数、组件质量、弹药压力曲线），游戏空间用 PhysX；", "弹道与爆炸层用 ECS for Unity + Burst，实现更小子步采样与精确空气阻力；", "目标平台 Quest 3：CPU 侧靠 ECS/Burst，渲染侧严控多边形与纹理内存；", "重度依赖 Odin Inspector 与 Collider Creator 2 等编辑器工具。"] }, { title: "笔者观察", type: "text", text: "『双轨物理』是本篇最值得抄的架构决策：交互级模拟需要确定性小步长，世界级模拟需要规模，硬塞进同一个物理引擎两头不讨好。另外『先花 6 个月搭基建再生产内容』对课程团队也适用——只是比例要按项目长度缩放，别真花一学期不写玩法。参考来源：Unity 官方博客。" }] },
    { id: "steam-demo-ccu-prediction", category: "tutorials", subcategory: "数据分析", title: "Demo 峰值 CCU ×3.01 ≈ 正式版峰值：GameDiscoverCo 用 2569 款游戏验证的估算公式", summary: "GameDiscoverCo 基于 2024-2026 年 2569 款 Steam 游戏的逐小时 CCU 数据得出：正式版历史峰值 CCU 约为 Demo 峰值的 3.01 倍（中位数），但方差极大（1.29x-6.24x+），实际估算建议用 2-4 倍基准再做品类修正。", source: "GameLook（编译自 GameDiscoverCo 研究）", date: "2026-09-24", url: "http://www.gamelook.com.cn/2026/09/602885/", image: "", badge: "数据分析", badgeType: "game", readTime: "8 分钟", hotScore: 88, tags: ["Steam", "Demo", "数据分析", "GameDiscoverCo"], content: [{ title: "方法要点", type: "list", items: ["样本：2024/1-2026/8 上线、Demo CCU>50 的 2569 款游戏；", "中位规律：正式版历史峰值 CCU ≈ Demo 峰值 CCU × 3.01；", "最好前 20-30% 的 Demo 转化达 6.24 倍，最差仅 1.29 倍；", "换算参考：Demo 200 CCU ≈ 正式版 600 CCU ≈ 首周约 1.2 万份、首年约 3.5 万份；", "2026 年 Steam 收入 Top100 中 58 款发售前放过 Demo。"] }, { title: "笔者观察", type: "text", text: "这份研究给所有准备发 Demo 的团队一个可执行的动作：发售前用『Demo 峰值×3』做销量基线，把营销预算押在转化倍数的方差上——钩子强度和执行质量决定了你落在 1.29 还是 6.24。超小团队尤其注意：Demo 热度高但正式版执行弱的反例（如 Drive Together）说明 Demo 只承诺『感兴趣』，不担保『满意』。参考来源：GameLook。" }] },
    { id: "wardogs-postmortem", category: "tutorials", subcategory: "数据复盘", title: "《Wardogs》首周 220 万份复盘：愿望单转化率 11% 是 3A 均值的两倍多", summary: "Alinea Insight 复盘 Bulkhead 的 PVP 战术射击《Wardogs》：首周 220 万份、约 7000 万美元收入，愿望单转化率 11%（典型 3A 约 5%）；57% 愿望单在发售前一个月添加；74% 好评率的主因是服务器与反作弊问题而非玩法。", source: "GameLook（编译自 Alinea Insight）", date: "2026-09-23", url: "http://www.gamelook.com.cn/2026/09/602831/", image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1867240/24c0b6c0621560e922fbed18545921e7eaa9036e/capsule_616x353.jpg?t=1789503126", badge: "数据复盘", badgeType: "game", readTime: "8 分钟", hotScore: 86, tags: ["Wardogs", "数据复盘", "Steam", "愿望单"], content: [{ title: "复盘要点", type: "list", items: ["首周销量 220 万份、收入约 7000 万美元，愿望单转化率 11%；", "57% 愿望单是发售前一个月添加，后期爆发型热度路线；", "玩家重合度：CS2 86.6%、PUBG 65.7%，与 Arc Raiders 仅 9.3%（吸引的是沙盒战术老玩家）；", "差评主因：服务器排队、Elytra 反作弊砍掉 Linux/Proton 支持；游戏时长 5 小时以上的玩家好评率 86%+。"] }, { title: "笔者观察", type: "text", text: "两条结论值得写进笔记：一是『社区比预算重要』——不到一年前还陷入财务困境的团队靠明确用户画像（孤独的 18-40 岁男性沙盒玩家）打出超预期转化；二是『好评率要按时长分层看』，<1 小时 42% 与 5 小时+ 86% 的差值说明差评几乎全是发售事故而非产品问题。做上线演练时，服务器容量与反作弊迁移方案要当成产品级风险管理。参考来源：GameLook。" }] },
    { id: "unity-cli-xr-5-tips", category: "tutorials", subcategory: "工作流", title: "Unity CLI 内置 MCP 服务器：XR 开发工作流的 5 个提速技巧", summary: "Meta 开发者倡导者 Dilmer Valecillos 在 Unity 官方博客分享 5 个技巧：Unity CLI 内置 MCP 服务器可直连 LLM 客户端，eval 命令借 Roslyn 毫秒级执行 C# 片段（免编译免域重载），配合 Meta VR CLI 做设备性能捕获与 A/B 分析。", source: "Unity 官方博客（一手来源）", date: "2026-09-17", url: "https://unity.com/blog/5-tips-for-speeding-up-your-xr-dev-workflows-with-unity-cli", image: "", badge: "工作流", badgeType: "engine", readTime: "6 分钟", hotScore: 72, tags: ["Unity CLI", "MCP", "XR", "AI 工作流"], content: [{ title: "技巧要点", type: "list", items: ["Unity CLI 内置 MCP 服务器，Cursor/Claude Code 等 LLM 客户端可直接连接；", "eval 命令通过 Roslyn 实时编译运行 C#，免编辑器重编译与域重载；", "建议多个 LLM 混用：一个写代码、另一个做代码审查；", "Meta VR CLI 自带 MCP 服务器：metavr perf capture 从 Quest 捕获性能数据定位瓶颈；", "核心心法：『减少证明问题存在的时间，增加解决问题的时间』。"] }, { title: "笔者观察", type: "text", text: "对非 XR 项目同样成立的部分是 eval+Roslyn 这条链路：绕过『改一行→重编译→域重载→再看效果』的循环，是 AI 时代迭代速度的真正杠杆。我们自己的调试工作流（TCP 桥执行 C# 探针）本质上就是同一思路的手工版。参考来源：Unity 官方博客。" }] },
    { id: "unity-learn-september", category: "tutorials", subcategory: "官方教程", title: "Unity Learn 九月上新：Input System、UI Toolkit 视频课与 Unity MCP 入门免费开放", summary: "Unity Learn 九月月度更新上线 5 项新内容：Input System 与 UI Toolkit 视频系列、Unity IAP 综合指南、Unity CLI 入门、Unity MCP 入门教程；官方预告后续将推出 Learn Shorts 短视频流与 AI 导师功能。", source: "Unity Discussions（Unity Learn 官方更新帖）", date: "2026-09-17", url: "https://discussions.unity.com/t/unity-learn-monthly-update-september-2026/1736869", image: "https://europe1.discourse-cdn.com/unity/original/3X/a/a/aaeab82727497b6f37f4312dcd57be21e6cd25e8.png", badge: "官方教程", badgeType: "engine", readTime: "3 分钟", hotScore: 64, tags: ["Unity Learn", "教程", "Input System", "UI Toolkit"], content: [{ title: "上新要点", type: "list", items: ["Input System Video Series：新版输入系统设置、配置与迁移；", "Unity IAP：应用内购设置与管理的综合指南；", "UI Toolkit Video Series：可扩展高性能界面设计基础；", "Unity CLI 入门与 Get Started with Unity MCP 两篇教程；", "预告：Learn Shorts 短视频流与 AI 导师功能即将推出。"] }, { title: "笔者观察", type: "text", text: "这批上新透出官方教学重点的迁移：Input System、UI Toolkit、CLI、MCP——全是『现代 Unity 工作流』的组件，而不是某个渲染特性。自学路线建议按这个顺序补课：先把 Input System 和 UI Toolkit 换掉旧习惯，再上 CLI/MCP 提效。参考来源：Unity Discussions。" }] },
    { id: "mihoyo-liuwei-ai-keynote", category: "ai", subcategory: "大厂动向", title: "米哈游刘伟立军令状：三年最高投入 1000 亿元，2-3 年内进国产大模型第一梯队", summary: "米哈游联合创始人刘伟在交大校招宣讲会公开表态：未来三年最多投入 1000 亿元深耕 AI，『2-3 年内成为国产大模型团队举足轻重的一员』；AI 千人千面游戏『三年之内就会出现』；蔡浩宇的《雨城》（UE5 开发）年底测试。", source: "GameLook", date: "2026-09-28", url: "http://www.gamelook.com.cn/2026/09/603053/", image: "", badge: "大厂动向", badgeType: "ai", readTime: "8 分钟", hotScore: 94, tags: ["米哈游", "AI 大模型", "千人千面", "雨城"], content: [{ title: "表态要点", type: "list", items: ["三年最多投入 1000 亿元做 AI；『没有坚定搞算力、scale，绝不可能把模型做到顶级』；", "目标 2-3 年内成为国产大模型第一梯队；做不到『随时过来打我脸』；", "AI+游戏愿景：千人千面的完全个性化体验，3 年之内出现；", "《雨城》（Varsapura）：蔡浩宇亲自制作、UE5 开发，支线深度融合 AI 动态交互，年底测试；", "关联布局：投资 MiniMax 已上市；Anuttacon 发布 LPM 1.0 视频角色表演模型。"] }, { title: "笔者观察", type: "text", text: "千人千面给的三年时限比大多数预测激进，但米哈游是少数同时握有内容工业线（米哈游）+模型线（MiniMax）+海外模型产品线（Anuttacon）的团队，纵向整合是成立的。对学生更实际的信号是人才结构：内容公司开始养模型团队，意味着『懂玩法又懂 LLM 工程化』的复合岗位会持续稀缺。参考来源：GameLook。" }] },
    { id: "veteran-dev-ai-5x", category: "ai", subcategory: "行业讨论", title: "30 年老鸟称 AI 让研发提速 5 倍却『毫无成就感』：社区吵翻了，两个数字都值得警惕", summary: "一位 30 年经验（20 年游戏工具+10 年 Unity）的开发者在社区发帖：AI 让研发提速约 5 倍、AI 写代码比人快 20 倍，但代价是成就感归零、初级岗断档、停用 AI 一个月就倒闭。社区质疑 5 倍数据，并指出疲惫只是被转移而非消失。", source: "GameLook（编译自海外社区讨论）", date: "2026-09-28", url: "http://www.gamelook.com.cn/2026/09/603042/", image: "", badge: "行业讨论", badgeType: "ai", readTime: "8 分钟", hotScore: 88, tags: ["AI 开发", "效率争议", "新人断档", "Unity"], content: [{ title: "讨论要点", type: "list", items: ["帖主：AI 让研发提速约 5 倍，AI 写代码比开发者快 20 倍且质量未降；", "代价：成就感丧失、失去工作量估算能力、初级岗被清场；", "20 年 3A 经验网友：开发者整天多线操作多个 Agent，『只剩最耗心力的顶层设计』；", "质疑方：学术研究通常只能复现 10%-50% 提升；写代码只占全部工作约 20%；", "新人断档解法讨论：师徒制+『让初级程序员离 AI 尽可能远』。"] }, { title: "笔者观察", type: "text", text: "双方都别全信：5 倍大概率是『样板间数字』（只算写代码环节），但『初级岗消失导致 3-5 年后无人接班』这个推演逻辑很扎实，与各行各业都在发生的事一致。对在校学生的实操建议：用 AI 加速学习而非替代练习——基础功还是要自己写，否则你就是那批『断档的中间层』。参考来源：GameLook。" }] },
    { id: "everweave-ai-ttrpg-revenue", category: "ai", subcategory: "AI 游戏商业", title: "AI 跑团手游《Everweave》月流水破 300 万：AI 互动叙事第一次跑出可复制的商业闭环", summary: "AI 跑团手游《Everweave》8 月移动端预估流水达 300 万元（Appmagic 数据），即将迈入累计千万行列，且 PC 版（everweave.ai）收入另计。与『AI 聊天皮』产品不同，它更像真正的跑团游戏，玩家『边吐槽边充值』。", source: "GameLook", date: "2026-09-23", url: "http://www.gamelook.com.cn/2026/09/602756/", image: "https://everweave.ai/og-image.jpg", badge: "AI 商业", badgeType: "ai", readTime: "6 分钟", hotScore: 82, tags: ["Everweave", "AI 跑团", "互动叙事", "商业化"], content: [{ title: "数据要点", type: "list", items: ["8 月移动端预估流水 300 万元，过去两个月收入大涨；", "PC 版收入另计，即将进入累计收入千万行列；", "差异化：做『更像真正的游戏』而非 AI 聊天机器人；", "玩家口碑两极：边吐槽生成质量、边持续付费。"] }, { title: "笔者观察", type: "text", text: "AI 叙事产品此前一直卡在『Demo 惊艳、留存难看』，《Everweave》的价值是证明跑团结构（回合、骰子、日程化推进）能给生成式内容装上『节奏骨架』，把无限自由收敛成可付费的循环。做 AI 玩法原型的同学记住这个公式：生成式内容×传统玩法骨架=可留存产品。参考来源：GameLook。" }] },
    { id: "wrtn-ooc-100m", category: "ai", subcategory: "AI 游戏商业", title: "韩国 Wrtn 冲刺 1 亿美元年收入：AI 角色叙事『一门三牌』打穿韩日美三地", summary: "首尔公司 Wrtn Technologies 围绕 AI 角色互动叙事运营 OOC、Crack、Kyarapu 三个品牌（同一套商业模式），移动端月流水超 4000 万元人民币；创始人 2 月披露 2025 年底年化收入 7000 万美元，2026 年目标超 1 亿美元，还拿下 G-STAR 主赞助商。", source: "GameLook", date: "2026-09-22", url: "http://www.gamelook.com.cn/2026/09/602693/", image: "", badge: "AI 商业", badgeType: "ai", readTime: "6 分钟", hotScore: 76, tags: ["Wrtn", "OOC", "AI 角色", "互动叙事"], content: [{ title: "数据要点", type: "list", items: ["Wrtn 2021 年成立，早期做 AI 写作辅助，现聚焦 AI 角色互动叙事；", "OOC（北美）/Crack（韩国）/Kyarapu（日本）指向同一套商业模式；", "移动版月流水合计超 4000 万元人民币；累计融资 7350 万美元（B 轮）；", "2025 年底年化收入 7000 万美元，2026 年目标超 1 亿美元；", "拿下 2026 韩国 G-STAR 游戏展主赞助商。"] }, { title: "笔者观察", type: "text", text: "Wrtn 的打法证明 AI 角色叙事是个『本地化密集型』生意：同一套技术底座，每个市场换皮肤、换内容策略单独运营。这与传统游戏出海的『全球一包』思路相反。另外『它算不算游戏』的争论还在继续，但资本市场已经用收入投了票——做叙事玩法的同学要认真研究它的付费结构。参考来源：GameLook。" }] },
    { id: "adobe-topaz-closed", category: "ai", subcategory: "行业并购", title: "Adobe 完成收购 Topaz Labs：端侧 AI 增强模型加速进入创意工具链", summary: "Adobe 于 9 月 23 日确认完成对 AI 图像/视频增强开发商 Topaz Labs 的收购（6 月宣布）。Topaz 的 Gigapixel 等模型已进入 Photoshop，其 GPU 显存优化技术 NeuroStream 可在消费级硬件上本地运行更大 AI 模型——与游戏开发者直接相关的正是这部分端侧能力。", source: "CG Channel（行业媒体报道，附官方信息）", date: "2026-09-23", url: "https://www.cgchannel.com/2026/09/adobe-to-acquire-topaz-labs/", image: "https://news.adobe.com/news/2026/06/media_1442ea3699b2ecf6a2b0e8c31b33b8795cc75f01e.png?width=1200&format=pjpg&optimize=medium", badge: "行业并购", badgeType: "ai", readTime: "5 分钟", hotScore: 70, tags: ["Adobe", "Topaz Labs", "端侧 AI", "并购"], content: [{ title: "交易要点", type: "list", items: ["6 月宣布、9 月 23 日完成收购；CEO Eric Yang 加入 Adobe 并继续领导团队；", "Topaz 2025 年年收入 4800 万美元，曾获技术艾美奖（档案电视修复）；", "已有 5 个 Topaz AI 模型可用于 Adobe 产品（含 Firefly）；", "NeuroStream GPU 显存优化：让消费级硬件本地运行更大 AI 模型；", "部分 CG 艺术家已用 Gigapixel 做『低分辨率渲染+AI 放大』提速管线。"] }, { title: "笔者观察", type: "text", text: "对游戏人来说这笔并购的看点不是 Photoshop，而是『低分辨率渲染+AI 超分』被主流工具链承认：它把渲染预算与画面保真度解耦，对移动端和小显存设备是实打实的省钱路线。端侧小模型的军备竞赛（Adobe 买 Topaz、NVIDIA 更新 ACE）都指向同一个方向。参考来源：CG Channel。" }] }
  ]
};
