/**
 * 广药 游戏开发情报中枢 · 每日技术情报 - 2026-09-19
 */

window.DAILY_NEWS_DATA = {
  meta: {
    date: "2026-09-19",
    weekday: "星期六",
    title: "广药 游戏开发情报中枢 · 每日技术情报",
    subtitle: "全生态技术演进 · 3A工业化与前沿行业情报",
    updateTime: "2026-09-19 08:00",
    editor: "广药技术中枢 & 豆包极客",
    highlights: [
      "TGS 2026公众日首日：Silent Hill Townfall 90分钟专场，Lollipop Chainsaw新企划舞台公开",
      "Xbox四大工作室脱离微软：Double Fine/Compulsion回归独立，Ninja Theory/Undead Labs易主",
      "Devolver Digital退出伦交所：90%股东投票，股价跌至0.16英镑约0.6倍市销率",
      "TGS现场：MSI RTX 5090 Lightning Z显卡+Claw 8 EX掌机亮相，万代南梦宫皇牌空战8可试玩",
      "Metro 2039正式公布，FF7重制版三部曲终章定档2027年4月8日"
    ],
    engineStatus: [
      { name: "Unity 6.6", type: "unity", status: "9/1正式发布·最佳生产版本指南更新", badge: "推荐生产", color: "indigo" },
      { name: "Unity 7", type: "unity", status: "CEDEC 2026公布AI/CoreCLR路线", badge: "下一代", color: "blue" },
      { name: "团结引擎 1.9.0", type: "tuanjie", status: "全局动态光照移动端并行渲染", badge: "移动端", color: "cyan" },
      { name: "UE 5.8", type: "unreal", status: "Epic确认5.9为UE6过渡桥接版", badge: "UE5收尾", color: "purple" },
      { name: "Godot 4.8 dev6", type: "godot", status: "9/15发布·macOS/Android Hotfix", badge: "开发版", color: "emerald" },
      { name: "Bevy 0.17.3", type: "godot", status: "Rust ECS·0.17迁移指南发布", badge: "Rust新秀", color: "pink" }
    ]
  },
  hero: {
    id: "hero-tgs2026-public-day1",
    category: "games",
    categoryName: "热门游戏 · 头条深度",
    tag: "TGS 2026 公众日",
    title: "TGS 2026公众日首日开幕：Silent Hill: Townfall 90分钟专场领衔，Lollipop Chainsaw新企划舞台首次公开",
    summary: "2026东京电玩展（TGS 2026）于9月19日迎来首个公众日。Konami在14:30-16:00安排了长达90分钟的《Silent Hill: Townfall》专场展示，这是该恐怖系列新作的最大规模公开亮相，游戏将于9月24日登陆PS5/Steam/Epic。上午9:40，《Lollipop Chainsaw》全新企划在活动舞台首次公开，制作人须田刚一虽不参与，但FF15导演田畑端创立的JP UNIVERSE工作室负责开发，PS5版《Lollipop Chainsaw 2: Back2Back》确认2027年发售。此外万代南梦宫展台提供《皇牌空战8》实机试玩，MSI展出RTX 5090 Lightning Z显卡和Claw 8 EX AI+掌机。",
    image: "",
    source: "Konami / Gematsu / TGS官网",
    date: "2026-09-19",
    url: "https://tgs.cesa.or.jp/2026/en/program",
    readTime: "4 分钟深度",
    hotScore: 96,
    tags: ["TGS 2026", "Silent Hill Townfall", "Lollipop Chainsaw", "Konami", "公众日", "幕张Messe" ],
    content: [
      { title: "9月19日公众日重点活动", type: "list", items: ["09:40-10:30 Lollipop Chainsaw New Project舞台；", "11:40-12:30 30th Anniversary Title Talk Stage；", "14:30-16:00 Silent Hill: Townfall 90分钟专场；", "万代南梦宫：Ace Combat 8试玩需现场发券；", "MSI展台：RTX 5090 Lightning Z + Claw 8 EX AI+；", "SEGA/Atlus展台：Lollipop Chainsaw 2四台试玩机；", "TGS 30周年纪念票同步发售。"] },
      { title: "行业分析", type: "text", text: "TGS 2026公众日首日是日本游戏行业年度最大的线下展示窗口。Silent Hill: Townfall选择在TGS进行90分钟深度展示，表明Konami对该IP的重启信心。Lollipop Chainsaw 2由FF15导演田畑端的JP UNIVERSE开发，显示了日本老牌IP在新工作室手中的转型。从硬件角度看，MSI在TGS展示RTX 5090 Lightning Z和新一代掌机，反映了TGS已经成为PC硬件厂商展示新品的重要舞台。" }
    ]
  },
  categories: [
    { id: "all", name: "全部资讯", icon: "🔥", desc: "汇总今日游戏开发全生态情报" },
    { id: "engine", name: "引擎前沿", icon: "🔧", desc: "Unity / 团结引擎 / 虚幻引擎 / Godot / 渲染技术" },
    { id: "industry", name: "行业热点", icon: "📰", desc: "大厂动向 / 财报 / 投融资 / 市场分析" },
    { id: "games", name: "热门游戏", icon: "🎮", desc: "新作发售 / 展会发布 / 热门追踪" },
    { id: "opensource", name: "开源宝库", icon: "⭐", desc: "GitHub 精选开源库 / 工具链 / 引擎框架" },
    { id: "tutorials", name: "实战教程", icon: "📚", desc: "DOTS / C# / 性能优化 / 架构设计" },
    { id: "ai", name: "AI前沿", icon: "🤖", desc: "AI NPC / 智能体 / 生成式AI / 大模型工具" }
  ],
  items: [
    { id: "xbox-four-studios-separate", category: "industry", subcategory: "微软重组", title: "Xbox四大工作室正式脱离微软：Double Fine/Compulsion回归独立，Ninja Theory/Undead Labs易主", summary: "据The Verge报道，微软Xbox重组方案正式落地：Double Fine和Compulsion Games将回归创始人独立运营；Ninja Theory和Undead Labs已签署协议加入新所有权。这是微软Xbox史上最大规模的工作室剥离事件，紧随新CEO Asha Sharma上任后的重置战略。四间工作室的脱离标志着Xbox第一方阵营从收购扩张转向精简聚焦。", source: "The Verge / Gamer Matters", date: "2026-09-18", url: "https://gamermatters.com/tag/compulsion-games/feed/", image: "", badge: "工作室剥离", badgeType: "business", readTime: "3 分钟", hotScore: 93, tags: ["Xbox", "Double Fine", "Compulsion Games", "Ninja Theory", "Undead Labs", "微软重组" ], content: [{ title: "剥离详情", type: "list", items: ["Double Fine回归Tim Schafer独立；", "Compulsion Games回归Guillaume Provost独立；", "Ninja Theory签署新所有权协议；", "Undead Labs签署新所有权协议；", "新CEO Asha Sharma重置战略；", "Xbox史上最大规模工作室剥离。"] }, { title: "行业影响", type: "text", text: "四间工作室同时脱离Xbox，标志着微软从2018-2021年的疯狂收购扩张转向精简聚焦战略。Double Fine和Compulsion回归创始人，Ninja Theory和Undead Labs易主，这意味着Xbox第一方阵容将大幅缩减。结合此前Xbox裁员3200人的消息，微软的游戏业务正在经历从规模扩张到效率优先的深度转型。" }] },
    { id: "silent-hill-townfall-tgs", category: "games", subcategory: "Konami", title: "Silent Hill: Townfall TGS专场9月24日发售：PS5/Steam/Epic三平台，90分钟深度展示", summary: "Konami在TGS 2026公众日首日为《Silent Hill: Townfall》安排了90分钟专场展示。游戏确认9月24日发售，登陆PS5、Steam和Epic。系列全球累计销量超1710万份。本次TGS专场是该恐怖IP重启后最大规模公开亮相，由Konami与Annapurna Interactive合作开发。", source: "Konami / Gematsu", date: "2026-09-19", url: "https://www.konami.com/games/eu/en/topics/19146/", image: "", badge: "9/24发售", badgeType: "game", readTime: "2 分钟", hotScore: 88, tags: ["Silent Hill Townfall", "Konami", "恐怖游戏", "9月24日", "PS5", "TGS 2026" ], content: [{ title: "发售信息", type: "list", items: ["9月24日正式发售；", "PS5/Steam/Epic三平台；", "TGS 9/19 14:30-16:00专场；", "系列全球销量超1710万份；", "Konami与Annapurna合作。"] }, { title: "摘要速读", type: "text", text: "Silent Hill: Townfall于9月24日发售，TGS 9/19安排90分钟专场。系列全球销量超1710万份，是恐怖IP重启代表作。" }] },
    { id: "konami-psychic-force-port", category: "games", subcategory: "经典移植", title: "Konami宣布Psychic Force 2012移植：经典格斗游戏时隔20余年登陆现代平台", summary: "Konami在TGS 2026期间宣布经典格斗游戏《Psychic Force 2012》将推出移植版。9月18日举行了Port Announcement特别活动，邀请原版音响导演和声优回顾经典。Psychic Force 2012是1998年街机格斗游戏，以超能力战斗为特色。这一移植标志着Konami在TGS 2026上的经典IP复活策略。", source: "Konami TGS Special Site", date: "2026-09-18", url: "https://www.konami.com/games/tgs/en/", image: "", badge: "经典移植", badgeType: "game", readTime: "2 分钟", hotScore: 75, tags: ["Psychic Force 2012", "Konami", "格斗游戏", "经典移植", "TGS 2026" ], content: [{ title: "移植信息", type: "list", items: ["TGS 9/18宣布；", "原版1998年街机格斗；", "超能力战斗特色；", "音响导演和声优嘉宾回顾；", "时隔20余年移植现代平台。"] }, { title: "摘要速读", type: "text", text: "Konami在TGS宣布Psychic Force 2012移植版，原版1998年街机格斗，时隔20余年登陆现代平台。" }] },
    { id: "com2us-gachiakuta-breakout", category: "games", subcategory: "TGS发布", title: "Com2Us公布Gachiakuta: Breakout首支实机：Xbox TGS展播，2027年多平台发售", summary: "韩国开发商Com2Us在Xbox TGS 2026展播中正式公布《GACHIAKUTA: BREAKOUT》标题和首支实机玩法预告片。游戏将于2027年登陆PS5、Xbox Series X|S和PC。Gachiakuta改编自同名漫画，以废土世界为背景。这是Com2Us从手游向主机3A转型的重要作品。", source: "GameTrader.SG", date: "2026-09-18", url: "https://www.gametrader.sg/blog/tag/tgs-2026/", image: "", badge: "Com2Us", badgeType: "game", readTime: "2 分钟", hotScore: 76, tags: ["Gachiakuta Breakout", "Com2Us", "Xbox TGS", "2027", "PS5" ], content: [{ title: "游戏信息", type: "list", items: ["Xbox TGS 2026展播公布；", "GACHIAKUTA: BREAKOUT；", "首支实机玩法预告片；", "2027年PS5/Xbox/PC；", "改编自同名漫画；", "Com2Us主机3A转型。"] }, { title: "摘要速读", type: "text", text: "Com2Us在Xbox TGS展播公布Gachiakuta: Breakout首支实机，2027年登陆PS5/Xbox/PC。改编自同名漫画，是Com2Us从手游向主机3A转型的重要作品。" }] },
    { id: "msi-rtx5090-claw8-tgs", category: "industry", subcategory: "硬件", title: "MSI TGS 2026展出RTX 5090 Lightning Z显卡+Claw 8 EX AI+掌机，规格待公布", summary: "MSI在TGS 2026上带来了最受关注的硬件展品：GeForce RTX 5090 LIGHTNING Z显卡和Claw 8 EX AI+掌机。MSI在展会上确认了两款设备的存在，但未公布价格、上市时间、核心频率、功耗限制、屏幕规格、重量或电池续航等具体参数。", source: "FraggedLife", date: "2026-09-18", url: "https://www.fraggedlife.com/blog/tokyo-game-show-2026-announcements", image: "", badge: "硬件新品", badgeType: "business", readTime: "2 分钟", hotScore: 78, tags: ["MSI", "RTX 5090 Lightning Z", "Claw 8 EX", "TGS 2026", "掌机" ], content: [{ title: "硬件信息", type: "list", items: ["RTX 5090 LIGHTNING Z显卡；", "Claw 8 EX AI+掌机；", "TGS 2026现场确认；", "价格/频率/功耗/屏幕均未公布；", "更偏概念展示。"] }, { title: "摘要速读", type: "text", text: "MSI在TGS 2026展出RTX 5090 Lightning Z和Claw 8 EX AI+掌机，但仅确认存在，未公布任何规格参数。" }] },
    { id: "devolver-digital-delisting", category: "industry", subcategory: "资本市场", title: "Devolver Digital退出伦交所AIM：90%股东赞成摘牌，股价跌至0.16英镑约0.6倍市销率", summary: "据InvestGame报道，独立游戏发行商Devolver Digital（AIM: DEVO）股东以90%票数赞成取消AIM上市资格，摘牌自2026年9月16日起生效。股价从五年前IPO时的1.57英镑跌至0.16英镑，约为0.6倍市销率。Devolver发行过《Hotline Miami》《Carrion》《Fall Guys》等作品。", source: "InvestGame", date: "2026-09-19", url: "https://investgame.net/", image: "", badge: "摘牌退市", badgeType: "business", readTime: "3 分钟", hotScore: 84, tags: ["Devolver Digital", "伦交所AIM", "摘牌", "0.6倍市销率", "独立发行商" ], content: [{ title: "摘牌详情", type: "list", items: ["90%股东赞成取消上市；", "9月16日起生效；", "股价从1.57英镑跌至0.16英镑；", "约0.6倍市销率；", "五年前IPO价1.57英镑。"] }, { title: "行业意义", type: "text", text: "Devolver Digital的摘牌是独立游戏发行行业2026年困境的标志性事件。作为独立游戏发行领域最具品牌影响力的公司之一，Devolver从2021年上市时的高光到2026年摘牌，反映了独立游戏行业从疫情期繁荣到后疫情期收缩的完整周期。" }] },
    { id: "japan-defies-layoff-trend", category: "industry", subcategory: "行业趋势", title: "日本游戏业逆势扩张：2022-2026全球57628个游戏岗位消失，日本却独善其身", summary: "据XGN报道，据Layoffs Tracker管理Amir Satvat统计，2022年至2026年全球游戏行业预计将消失57628个工作岗位。北美和西欧3A开发商的裁员浪潮被类比为1983年游戏业大崩溃。然而日本游戏行业却呈现完全不同的趋势——尽管微软Xbox裁员3200人、Epic Games裁员超1000人，日本游戏公司在TGS 2026期间持续扩张和招聘。", source: "XGN / Le Mag Jeux Video", date: "2026-09-18", url: "https://www.xgn.nl/nieuws/gamebedrijven-ontslaan-massaal-personeel-maar-japan-lijkt-de-dans-te-ontspringen", image: "", badge: "行业对比", badgeType: "business", readTime: "3 分钟", hotScore: 83, tags: ["游戏裁员", "日本游戏业", "57628岗位", "Layoffs Tracker" ], content: [{ title: "数据对比", type: "list", items: ["2022-2026全球消失57628岗位；", "北美西欧被类比1983大崩溃；", "微软Xbox裁员3200人；", "Epic Games裁员超1000人；", "日本游戏业逆势扩张。"] }, { title: "分析", type: "text", text: "日本游戏业与西方的分化值得深思：西方3A开发商受GAAS模式失败和收购整合成本拖累，而日本厂商凭借更健康的项目管线和更长期的人才培养模式，在裁员潮中保持了扩张。TGS 2026本身就是这一分化的缩影。" }] },
    { id: "take-two-ai-division-layoff", category: "industry", subcategory: "AI部门裁员", title: "Take-Two解散AI部门：AI主管Luke Dicken及团队被裁，程序化生成内容战略受挫", summary: "Take-Two Interactive解雇了其AI部门负责人Luke Dicken及多名团队成员。虽然具体裁员人数未公开，但此举是Take-Two更大规模成本削减重组的一部分。这一裁员引发了关于AI在游戏行业角色的讨论——尽管多家公司在投资AI游戏工具，但Take-Two的AI部门解散表明，将AI视为独立业务部门的战略在实际运营中面临挑战。", source: "OpenTools.ai", date: "2026-09-16", url: "https://opentools.ai/news/take-two-interactive-shakes-up-with-ai-division-layoff", image: "", badge: "AI部门解散", badgeType: "business", readTime: "2 分钟", hotScore: 79, tags: ["Take-Two", "AI部门裁员", "Luke Dicken", "程序化生成" ], content: [{ title: "事件要点", type: "list", items: ["AI部门主管Luke Dicken被裁；", "具体人数未公开；", "Take-Two成本削减重组一部分；", "AI独立业务部门战略面临挑战。"] }, { title: "摘要速读", type: "text", text: "Take-Two解散AI部门，主管Luke Dicken及团队被裁。这是成本削减重组一部分，表明将AI作为独立业务部门的战略在实际运营中面临挑战。" }] },
    { id: "take-two-gta-online-continues", category: "games", subcategory: "R星", title: "Take-Two CEO确认：GTA Online不会随GTA 6发售而结束，将长期继续运营", summary: "Take-Two CEO Strauss Zelnick在股东问答环节明确确认：《GTA Online》不会随《GTA 6》发售而结束，将在新作推出后及更长时间内继续为现有在线模式提供支持。这意味着R星将同时运营两代GTA在线模式，这在R星历史上尚无先例。GTA 6预计2026年底发售。", source: "凤凰网科技", date: "2026-09-18", url: "https://tech.ifeng.com/c/8wVrKkhkw5t", image: "", badge: "官方确认", badgeType: "game", readTime: "2 分钟", hotScore: 81, tags: ["Take-Two", "GTA Online", "GTA 6", "Strauss Zelnick", "R星" ], content: [{ title: "官方表态", type: "list", items: ["CEO Strauss Zelnick股东问答确认；", "GTA Online不会随GTA 6结束；", "新作推出后长期继续运营；", "R星将同时运营两代在线模式；", "GTA 6预计2026年底发售。"] }, { title: "摘要速读", type: "text", text: "Take-Two CEO确认GTA Online不会随GTA 6发售而结束，将长期继续运营。这意味着R星将同时运营两代GTA在线模式。" }] },
    { id: "metro-2039-revealed", category: "games", subcategory: "State of Play", title: "Metro 2039正式公布：4A Games后启示录射击新作，State of Play首次公开", summary: "在9月17日的PlayStation State of Play直播中，4A Games正式公布了《Metro 2039》。这是Metro系列的最新正统续作，延续后启示录莫斯科地铁的设定。State of Play同时公布了Final Fantasy VII重制版三部曲终章将于2027年4月8日发售。Metro系列以其压抑的氛围、叙事驱动的射击玩法和出色的画面表现著称。", source: "STG Play / PlayStation", date: "2026-09-17", url: "https://www.shanethegamer.com/news/state-of-play-september-2026-everything-announced/", image: "", badge: "Metro新作", badgeType: "game", readTime: "2 分钟", hotScore: 82, tags: ["Metro 2039", "4A Games", "State of Play", "后启示录", "FPS" ], content: [{ title: "发布信息", type: "list", items: ["State of Play 9/17公布；", "Metro系列正统续作；", "4A Games开发；", "后启示录莫斯科地铁设定；", "同时公布FF7终章2027年4月8日。"] }, { title: "摘要速读", type: "text", text: "4A Games在State of Play公布Metro 2039，延续后启示录地铁设定。同时State of Play还公布了FF7重制版三部曲终章2027年4月8日发售。" }] },
    { id: "lego-batman-switch2", category: "games", subcategory: "Switch 2", title: "乐高蝙蝠侠：黑暗骑士之遗登陆Switch 2：9月18日发售，标准版$70豪华版$90", summary: "TT Games开发的《乐高蝙蝠侠：黑暗骑士之遗》于9月18日登陆Nintendo Switch 2。游戏标准版售价70美元，豪华版90美元。该作此前已于5月23日登陆PS5、Xbox Series X|S和PC。这是乐高系列首次登陆Switch 2平台，支持简体中文。", source: "Engadget", date: "2026-09-18", url: "https://www.engadget.com/2186891/lego-batman-legacy-of-the-dark-knight-is-headed-to-the-switch-2-on-september-18/", image: "", badge: "Switch 2", badgeType: "game", readTime: "2 分钟", hotScore: 73, tags: ["乐高蝙蝠侠", "Switch 2", "TT Games", "9月18日" ], content: [{ title: "发售信息", type: "list", items: ["9月18日登陆Switch 2；", "标准版$70豪华版$90；", "TT Games开发；", "此前5/23已登陆PS5/Xbox/PC；", "支持简体中文。"] }, { title: "摘要速读", type: "text", text: "《乐高蝙蝠侠：黑暗骑士之遗》9月18日登陆Switch 2，标准版$70豪华版$90。此前已登陆PS5/Xbox/PC。" }] },
    { id: "fire-emblem-fortunes-weave", category: "games", subcategory: "任天堂", title: "火焰纹章：Fortune's Weave 9月17日发售：任天堂战略RPG系列最新作登陆Switch 2", summary: "任天堂《火焰纹章》系列最新作《Fire Emblem: Fortune's Weave》于9月17日发售，登陆Nintendo Switch 2。这是火焰纹章系列在Switch 2平台的首个作品，延续了系列经典的战棋玩法和角色羁绊系统，同时利用Switch 2的硬件能力提升画面表现。", source: "Sortiraparis / Game Informer", date: "2026-09-17", url: "https://www.sortiraparis.com/en/articles/tag/video-game-releases-september-guide", image: "", badge: "Switch 2首发", badgeType: "game", readTime: "2 分钟", hotScore: 77, tags: ["火焰纹章", "Fire Emblem", "Fortune's Weave", "Switch 2", "任天堂", "战棋" ], content: [{ title: "发售信息", type: "list", items: ["9月17日发售；", "登陆Nintendo Switch 2；", "系列Switch 2首个作品；", "经典战棋+角色羁绊系统；", "利用Switch 2硬件提升画面。"] }, { title: "摘要速读", type: "text", text: "《火焰纹章：Fortune's Weave》9月17日登陆Switch 2，是系列在Switch 2平台的首个作品，延续经典战棋+角色羁绊系统。" }] },
    { id: "unity-cedec-2026-sessions", category: "engine", subcategory: "Unity CEDEC", title: "Unity CEDEC 2026三场演讲：AI活用案例、图形最新功能、CoreCLR迁移实战", summary: "Unity Technologies Japan在CEDEC 2026上举办了三场技术演讲，涵盖Unity AI活用案例、图形学最新功能和CoreCLR迁移实践。CEDEC是日本最大的游戏开发者技术会议。Unity在展会上展示了其AI工具链在实际游戏开发中的应用案例，以及CoreCLR迁移到.NET的最新进展。", source: "Unity Technologies Japan", date: "2026-09-18", url: "https://unity3d.jp/news/unity-cedec-2026/", image: "", badge: "CEDEC 2026", badgeType: "engine", readTime: "2 分钟", hotScore: 76, tags: ["Unity", "CEDEC 2026", "AI活用", "CoreCLR", "日本开发者大会" ], content: [{ title: "三场演讲", type: "list", items: ["Unity AI活用案例；", "图形学最新功能；", "CoreCLR迁移实践；", "CEDEC日本最大游戏开发者大会；", "对迁移Unity 7团队有参考价值。"] }, { title: "摘要速读", type: "text", text: "Unity在CEDEC 2026举办三场演讲：AI活用案例、图形最新功能、CoreCLR迁移实践。对计划迁移Unity 7的团队有参考价值。" }] },
    { id: "unity-66-best-version-guide", category: "engine", subcategory: "Unity版本选择", title: "Unity 6.6成为新项目最佳推荐版本：9月18日更新生产版本指南，Path to CoreCLR+C# 14", summary: "据Makaka Games 9月18日更新的Unity版本推荐指南，Unity 6.6（2026年9月1日发布）目前是新项目的最佳推荐版本。6.6版本的关键新特性包括：Path to CoreCLR、.NET 10和C# 14，以及默认启用Fast Enter Play Mode。指南建议新项目直接使用6.6而非6.3 LTS。", source: "Makaka Games", date: "2026-09-18", url: "https://makaka.org/unity-tutorials/best-version", image: "", badge: "版本指南", badgeType: "engine", readTime: "3 分钟", hotScore: 79, tags: ["Unity 6.6", "版本推荐", "CoreCLR", ".NET 10", "C# 14" ], content: [{ title: "推荐理由", type: "list", items: ["9月18日更新指南；", "6.6为新项目最佳推荐；", "Path to CoreCLR+.NET 10+C# 14；", "Fast Enter Play Mode默认启用；", "新项目直接用6.6而非6.3。"] }, { title: "摘要速读", type: "text", text: "Makaka Games更新Unity版本指南，推荐新项目直接使用Unity 6.6，包含CoreCLR路径、.NET 10、C# 14和Fast Enter Play Mode。" }] },
    { id: "unity-content-directories", category: "tutorials", subcategory: "Unity架构", title: "Unity 6.6 Content Directories深度解析：47000资产项目的内容组织与底层变更实战", summary: "ProjectMakers发布Unity 6.6 Content Directories深度技术文章，以一个含47000个资产的真实项目为例，解析Unity 6.6新引入的Content Directories系统如何改变大型项目的资产组织方式。文章涵盖内容目录的配置、迁移策略、对现有项目的影响，以及底层渲染和资源管理的变更。", source: "ProjectMakers", date: "2026-09-05", url: "https://projectmakers.de/en/blog/unity-66-released-what-content-directories", image: "", badge: "架构实战", badgeType: "engine", readTime: "3 分钟", hotScore: 74, tags: ["Unity 6.6", "Content Directories", "大型项目", "资产组织" ], content: [{ title: "文章要点", type: "list", items: ["以47000资产真实项目为例；", "Content Directories系统详解；", "配置与迁移策略；", "底层渲染和资源管理变更；", "Unity 6.x最具架构影响功能。"] }, { title: "摘要速读", type: "text", text: "ProjectMakers深度解析Unity 6.6 Content Directories，以47000资产项目为例讲解新内容目录系统的配置、迁移和底层变更。" }] },
    { id: "nimble-fox-ai-unity-launch", category: "ai", subcategory: "AI游戏工具", title: "Nimble Fox AI Unity开发工具公开上线：赫尔辛基初创，游戏内直接描述构建功能", summary: "据GamesBeat报道，赫尔辛基初创公司Nimble Fox于9月7日公开发布其AI驱动的Unity开发工具。开发者可以在Unity引擎内直接用自然语言描述需求，Nimble Fox即构建和修改游戏功能。与一次性生成完整游戏不同，Nimble Fox采用渐进式构建模式。平台上线时提供免费和付费计划。", source: "GamesBeat", date: "2026-09-07", url: "https://gamesbeat.com/nimble-fox-launches-ai-tool-for-building-unity-games-worldwide/", image: "", badge: "AI Unity", badgeType: "ai", readTime: "2 分钟", hotScore: 77, tags: ["Nimble Fox", "AI Unity", "赫尔辛基", "渐进式构建" ], content: [{ title: "工具特点", type: "list", items: ["9月7日公开发布；", "赫尔辛基初创公司；", "Unity引擎内直接自然语言描述；", "渐进式构建而非一次性生成；", "免费和付费计划。"] }, { title: "摘要速读", type: "text", text: "赫尔辛基初创Nimble Fox AI Unity工具9/7公开上线，引擎内自然语言描述构建功能，采用渐进式构建模式。" }] },
    { id: "godot-openxr-vendors-v51", category: "opensource", subcategory: "Godot XR", title: "Godot OpenXR Vendors插件v5.1发布：新增多个Android XR特性，VR/AR开发持续完善", summary: "Godot官方发布OpenXR Vendors插件v5.1版本，新增多项Android XR特性。该插件为Godot引擎提供OpenXR运行时支持，覆盖主流VR/AR设备的厂商扩展。v5.1版本特别增强了Android XR平台的支持。Godot作为开源引擎，其XR生态正在逐步完善。", source: "Godot Engine Blog", date: "2026-09-15", url: "https://godotengine.org/blog/", image: "", badge: "OpenXR v5.1", badgeType: "engine", readTime: "2 分钟", hotScore: 72, tags: ["Godot", "OpenXR", "v5.1", "Android XR", "VR/AR" ], content: [{ title: "更新要点", type: "list", items: ["OpenXR Vendors插件v5.1；", "新增多个Android XR特性；", "覆盖主流VR/AR设备厂商扩展；", "Godot XR生态持续完善。"] }, { title: "摘要速读", type: "text", text: "Godot OpenXR Vendors插件v5.1发布，新增Android XR特性，为开源VR/AR开发者提供不依赖商业引擎的XR开发选择。" }] },
    { id: "soda-game-engine-rewrite", category: "opensource", subcategory: "新引擎", title: "Soda游戏引擎重写：基于MiniScript的跨平台开源引擎，从C++/SDL转向更易构建架构", summary: "JoeStrout宣布Soda游戏引擎正在重写。Soda是一个基于MiniScript编程语言的开源跨平台游戏引擎，定位为简单有趣。原版Soda基于C++/SDL开发，但构建困难、扩展困难、发布困难。2026年起团队开始重写Soda，目标是让引擎更容易构建、扩展和发布。", source: "GitHub / JoeStrout", date: "2026-09-15", url: "https://github.com/JoeStrout/soda", image: "", badge: "新引擎", badgeType: "engine", readTime: "2 分钟", hotScore: 70, tags: ["Soda", "MiniScript", "开源引擎", "跨平台", "C++/SDL重写" ], content: [{ title: "重写原因", type: "list", items: ["基于MiniScript编程语言；", "原版C++/SDL构建困难；", "扩展困难发布困难；", "2026年起重写；", "目标更易构建/扩展/发布。"] }, { title: "摘要速读", type: "text", text: "Soda游戏引擎（基于MiniScript）正在重写，原版C++/SDL构建和扩展困难，新版目标是更易构建、扩展和发布。" }] },
    { id: "rpgjs-studio-cloud", category: "opensource", subcategory: "RPG引擎", title: "RPGJS Studio云工作区上线：开源2D RPG引擎+云端工作室+AI编码Agent直连", summary: "RPGJS推出Studio云工作区，这是一个面向2D RPG开发者的云端开发环境。RPGJS引擎本身保持免费开源，Studio提供地图设计、游戏数据管理、资产生成、项目导出等生产级工作流，并可直接连接AI编码Agent到RPG工作流。开发者可以在浏览器中设计地图、管理数据、生成资产并导出项目。", source: "RPGJS官网", date: "2026-09-15", url: "https://rpgjs.dev/", image: "", badge: "云工作区", badgeType: "ai", readTime: "2 分钟", hotScore: 73, tags: ["RPGJS", "2D RPG", "开源引擎", "云工作区", "AI编码Agent" ], content: [{ title: "Studio功能", type: "list", items: ["RPGJS引擎保持免费开源；", "Studio云工作区；", "地图设计/数据管理/资产生成/导出；", "AI编码Agent直连RPG工作流；", "浏览器中完成开发全流程。"] }, { title: "摘要速读", type: "text", text: "RPGJS Studio云工作区上线，开源2D RPG引擎+云端工作室+AI编码Agent直连，引擎保持免费。" }] },
    { id: "playcanvas-supersplat-api", category: "opensource", subcategory: "Web3D", title: "PlayCanvas SuperSplat发布Publishing API：Vibe Code Splat Apps+360视频+Splat-transform 3.0", summary: "PlayCanvas在8月发布SuperSplat的新Publishing API。上月已推出Vibe Code Splat Apps、360度视频和splat-transform 3.0，将splat（高斯泼溅）转化为可发布的实际应用。PlayCanvas平台已于7月以MIT协议在GitHub完全开源。", source: "PlayCanvas官网", date: "2026-08-17", url: "https://playcanvas.com/", image: "", badge: "Web3D", badgeType: "engine", readTime: "2 分钟", hotScore: 71, tags: ["PlayCanvas", "SuperSplat", "Publishing API", "高斯泼溅", "Web3D" ], content: [{ title: "新功能", type: "list", items: ["SuperSplat Publishing API；", "Vibe Code Splat Apps；", "360度视频支持；", "splat-transform 3.0；", "PlayCanvas 7月MIT开源。"] }, { title: "摘要速读", type: "text", text: "PlayCanvas SuperSplat发布Publishing API，配合Vibe Code Splat Apps和splat-transform 3.0，将高斯泼溅内容直接发布为可交互Web应用。" }] },
    { id: "kolpa-engine-opensource", category: "opensource", subcategory: "C++引擎", title: "KOLPA Engine开源：C/C++编写的游戏引擎，C99框架层+C++20引擎层，ECS+物理+C#脚本", summary: "KOLPA Engine是一个开源游戏引擎，使用C和C++编写。架构分为两层：C99框架层负责渲染、输入、音频和数学；C++20引擎层提供ECS、场景管理、物理、音频和C#脚本支持。KOLPA使用OpenGL作为渲染后端，定位为轻量级但功能完整的开源引擎选择。", source: "KOLPA Engine官网", date: "2026-08-05", url: "https://kolpa-engine.github.io/", image: "", badge: "开源引擎", badgeType: "engine", readTime: "2 分钟", hotScore: 69, tags: ["KOLPA", "开源引擎", "C/C++", "C99", "C++20", "ECS" ], content: [{ title: "架构特点", type: "list", items: ["C99框架层：渲染/输入/音频/数学；", "C++20引擎层：ECS/场景/物理/音频/C#脚本；", "OpenGL渲染后端；", "可作框架或完整引擎。"] }, { title: "摘要速读", type: "text", text: "KOLPA Engine开源，C99框架层+C++20引擎层双架构，提供ECS/物理/音频/C#脚本支持，OpenGL渲染后端。" }] },
    { id: "gdevelop-v56282", category: "opensource", subcategory: "无代码引擎", title: "GDevelop v5.6.282发布：GitHub 26.5K星，无代码事件系统+内置AI Agent，MIT开源", summary: "开源无代码游戏引擎GDevelop于9月11日发布v5.6.282版本。GDevelop在GitHub上拥有26553星，是最受欢迎的无代码游戏开发引擎之一。最新版本内置AI Agent，可以直接在编辑器内构建游戏逻辑、调整对象属性甚至替换素材。GDevelop基于MIT协议完全开源免费。", source: "MyGit / CSDN", date: "2026-09-11", url: "https://github.com/4ian/GDevelop", image: "", badge: "v5.6.282", badgeType: "engine", readTime: "2 分钟", hotScore: 74, tags: ["GDevelop", "无代码", "AI Agent", "MIT开源", "26.5K星" ], content: [{ title: "版本信息", type: "list", items: ["v5.6.282发布于9月11日；", "GitHub 26553星；", "内置AI Agent构建游戏逻辑；", "搭积木式事件系统；", "MIT协议完全开源。"] }, { title: "摘要速读", type: "text", text: "GDevelop v5.6.282发布，GitHub 26.5K星，无代码事件系统+内置AI Agent，MIT开源免费。" }] },
    { id: "decapolice-tgs-trailer", category: "games", subcategory: "Level-5", title: "LEVEL-5发布DECAPOLICE TGS实机预告：犯罪悬疑RPG三分钟玩法，试玩版同步上线", summary: "LEVEL-5在TGS 2026期间发布了犯罪悬疑RPG《DECAPOLICE》的三分钟实机玩法预告片。游戏在TGS现场提供试玩版，登陆PS5和Switch 2平台。DECAPOLICE是LEVEL-5继《妖怪手表》《闪电十一人》后的新作，以犯罪调查和推理为核心玩法。", source: "Gematsu", date: "2026-09-16", url: "https://www.gematsu.com/", image: "", badge: "犯罪悬疑", badgeType: "game", readTime: "2 分钟", hotScore: 71, tags: ["DECAPOLICE", "LEVEL-5", "犯罪悬疑", "PS5", "Switch 2" ], content: [{ title: "游戏信息", type: "list", items: ["三分钟实机预告片；", "TGS现场提供试玩版；", "PS5/Switch 2平台；", "犯罪调查和推理核心玩法；", "妖怪手表开发商新作。"] }, { title: "摘要速读", type: "text", text: "LEVEL-5在TGS发布DECAPOLICE三分钟实机预告，犯罪悬疑RPG，PS5/Switch 2平台，现场提供试玩版。" }] },
    { id: "godot-47-lights-camera-action", category: "engine", subcategory: "Godot版本", title: "Godot 4.7「Lights, Camera, Action!」开发日志：三年成熟后的Director's Cut级画质飞跃", summary: "Godot官方发布4.7版本开发日志「Lights, Camera, Action!」。Godot 4系列从最初的稳定性夯实阶段逐步过渡到精打磨和体验提升，4.7作为Director's Cut版本带来了前所未有的色彩和画质表现。4.7还引入了HDR输出（Windows/macOS）等新特性。当前稳定版为4.7.2，开发版为4.8 dev6。", source: "Godot Itch.io Devlog", date: "2026-09-07", url: "https://godotengine.itch.io/godot/devlog/1557382/godot-47-lights-camera-action", image: "", badge: "4.7精修", badgeType: "engine", readTime: "2 分钟", hotScore: 75, tags: ["Godot 4.7", "Lights Camera Action", "Director's Cut", "HDR输出" ], content: [{ title: "版本亮点", type: "list", items: ["开发日志Lights Camera Action；", "4.x系列三年成熟后精修；", "Director's Cut级色彩和画质；", "HDR输出（Windows/macOS）；", "当前稳定版4.7.2。"] }, { title: "摘要速读", type: "text", text: "Godot 4.7开发日志「Lights, Camera, Action!」发布，4.x系列三年成熟后进入Director's Cut级精修，带来前所未有的色彩和画质。" }] },
    { id: "ue6-roadmap-update", category: "engine", subcategory: "UE6路线图", title: "Epic官方确认UE5.9为UE6过渡桥接版：不再计划5.8后正式UE5版本，保留5.9选项", summary: "Epic Games在「The Road to Unreal Engine 6」官方文章中确认：目前不计划在5.8后发布另一个正式UE5版本，但保留在必要时发布5.9的选项。Fortnite开发将挂载到UE6流上，开发者可以实时查看正在进行的工作并cherry-pick变更。UE6流不是Alpha，仅用于透明展示方向。", source: "Unreal Engine官方", date: "2026-09-15", url: "https://www.unrealengine.com/news/the-road-to-ue-6", image: "", badge: "UE6路线", badgeType: "engine", readTime: "3 分钟", hotScore: 83, tags: ["UE6", "UE5.9", "Epic Games", "Fortnite", "UE5收官" ], content: [{ title: "官方表态", type: "list", items: ["不计划5.8后另一个正式UE5版本；", "保留必要时发布5.9选项；", "Fortnite挂载到UE6流；", "开发者可实时查看UE6工作；", "UE5剩余变更继续合并到UE6。"] }, { title: "开发者影响", type: "text", text: "Epic确认UE5正式收官对开发者有直接影响：使用UE5的项目将以5.8作为最终生产版本，新项目需要开始评估UE6的迁移路径。Fortnite挂载到UE6流意味着UE6将在实际大型项目中验证。" }] },
    { id: "tgs-30th-anniversary", category: "industry", subcategory: "TGS 2026", title: "TGS 2026迎来30周年：史上最长5天展期，小学生以下免费，特别纪念票同步发售", summary: "2026年东京电玩展迎来创办30周年纪念。今年TGS展期延长至史上最长5天（9月17-21日），其中9月17-18日为商务日，9月19-21日为公众日。小学生以下观众免费入场。TGS还发行了30周年纪念特别门票。今年在幕张Messe 1-11号馆举行。", source: "eSports World / TGS官网", date: "2026-09-19", url: "https://esports-world.jp/news/63228", image: "", badge: "30周年", badgeType: "event", readTime: "2 分钟", hotScore: 74, tags: ["TGS 2026", "30周年", "幕张Messe", "5天展期" ], content: [{ title: "30周年信息", type: "list", items: ["TGS创办30周年；", "史上最长5天展期（9/17-21）；", "9/17-18商务日，9/19-21公众日；", "小学生以下免费；", "30周年纪念特别票发售。"] }, { title: "摘要速读", type: "text", text: "TGS 2026迎来30周年，展期延长至史上最长5天，小学生以下免费，30周年纪念票同步发售。" }] },
    { id: "nascar-26-release", category: "games", subcategory: "9月18日发售", title: "NASCAR 26正式发售：PS5/Xbox Series/PC全平台，9月18日赛车游戏新作", summary: "EA的《NASCAR 26》于9月18日正式发售，登陆PS5、Xbox Series X|S和PC平台。这是NASCAR赛车游戏系列的最新作品，包含最新赛季的车手、车队和赛道。同日发售的还有《The Walking Dead: Streets of Survival》等多款游戏。", source: "Game Informer", date: "2026-09-18", url: "https://gameinformer.com/this-week", image: "", badge: "9/18发售", badgeType: "game", readTime: "2 分钟", hotScore: 68, tags: ["NASCAR 26", "EA", "赛车", "9月18日", "PS5" ], content: [{ title: "发售信息", type: "list", items: ["9月18日正式发售；", "PS5/Xbox Series/PC全平台；", "EA发行；", "最新赛季车手/车队/赛道。"] }, { title: "摘要速读", type: "text", text: "《NASCAR 26》9月18日全平台发售，EA发行，包含最新赛季车手车队赛道。" }] },
    { id: "crazy-climber-console-archives", category: "games", subcategory: "复古游戏", title: "Console Archives Crazy Climber 9月17日发售：PS5/Switch 2，南梦宫经典街机重制", summary: "南梦宫经典街机游戏《Crazy Climber》通过Console Archives系列于9月17日登陆PS5和Nintendo Switch 2。Console Archives是Hamster推出的经典街机重制系列。Crazy Climber是1980年发售的攀岩主题街机游戏，是早期动作游戏的代表作。这是Console Archives系列首次登陆Switch 2平台。", source: "Gematsu", date: "2026-09-17", url: "https://www.gematsu.com/", image: "", badge: "复古街机", badgeType: "game", readTime: "2 分钟", hotScore: 66, tags: ["Crazy Climber", "Console Archives", "南梦宫", "PS5", "Switch 2" ], content: [{ title: "发售信息", type: "list", items: ["9月17日发售；", "PS5/Switch 2平台；", "Hamster Console Archives系列；", "原版1980年南梦宫街机；", "系列首次登陆Switch 2。"] }, { title: "摘要速读", type: "text", text: "《Crazy Climber》通过Console Archives 9/17登陆PS5/Switch 2，原版1980年南梦宫攀岩街机，是该系列首次登陆Switch 2。" }] }
  ]
};
