window.DAILY_NEWS_DATA = {
  meta: {
    date: "2026-09-24",
    weekday: "星期四",
    title: "广药 游戏开发情报中枢 · 每日技术情报",
    subtitle: "全生态技术演进 · 3A工业化与前沿行业情报",
    updateTime: "2026-09-24 08:00",
    editor: "广药技术中枢 & 豆包极客",
    highlights: [
      "微软确认Sledgehammer Games参与开发下一款光环正传：动视全新团队+大锤工作室联合打造",
      "Xbox PC Remote Tools正式集成Unity 6.5：编辑器内一键远程构建部署到Windows设备",
      "SHINOBI: Art of Vengeance今日登陆Switch 2：掌机模式更高分辨率",
      "Fortnite推出AI驱动NPC定制工具：Epic进军生成式AI角色创作",
      "OmniCore AI插件登陆Unity：AI对话/语音/视觉/游戏状态解析全功能"
    ],
    engineStatus: [
      { name: "Unity 6.6", type: "unity", status: "9/1正式发布·WebGPU脱离实验版", badge: "推荐生产", color: "indigo" },
      { name: "Unity 7", type: "unity", status: "Unite Seoul公布·12月Beta·2027初发布", badge: "下一代", color: "blue" },
      { name: "团结引擎 1.10.3", type: "tuanjie", status: "9/9发布·持续更新", badge: "国内生态", color: "cyan" },
      { name: "UE 6", type: "unreal", status: "Rocket League首发·2027上线·UEFN合并", badge: "下一代", color: "purple" },
      { name: "Godot 4.8 dev6", type: "godot", status: "9/15发布·macOS/Android热修·月内特性冻结", badge: "开发中", color: "emerald" },
      { name: "Godot 4.7.2", type: "godot", status: "当前稳定版·生产推荐", badge: "LTS", color: "pink" }
    ]
  },
  hero: {
    id: "hero-sledgehammer-halo-confirmed",
    category: "industry",
    categoryName: "行业热点 · 头条深度",
    tag: "光环开发权尘埃落定",
    title: "微软确认Sledgehammer Games参与开发下一款光环正传：动视全新团队联合大锤工作室打造史上最棒Halo",
    summary: "微软9月24日正式确认，下一款光环正传作品将由动视旗下全新组建的专门团队与Sledgehammer Games联合开发，该团队独立于《使命召唤》现有开发计划。这是Xbox持续reset的最新进展：自7月以来的工作室剥离和裁员已完成约四分之三。Halo Studios（前343 Industries）将继续支持光环社区，但不再主导正传开发。COD系列受影响工作室包括Raven和Treyarch。动视豪言目标是打造史上最棒的光环游戏。",
    image: "",
    source: "Gaming Ideology / Xbox Wire / 游民星空",
    date: "2026-09-24",
    url: "https://www.gamingideology.com/microsoft-confirms-activision-and-sledgehammer-games-to-develop-next-mainline-ha/",
    readTime: "4 分钟深度",
    hotScore: 97,
    tags: ["Halo", "Sledgehammer", "Activision", "Xbox", "光环" ],
    content: [
      { title: "确认要点", type: "list", items: ["下一款光环正传由动视全新团队+Sledgehammer联合开发；", "团队独立于COD现有开发计划；", "Xbox reset完成约四分之三；", "Halo Studios继续支持社区但不主导正传；", "Raven和Treyarch受裁员影响；", "动视目标史上最棒光环。"] },
      { title: "行业影响", type: "text", text: "Sledgehammer Games的加入意味着光环正传将获得COD系列顶级3A射击开发经验的直接注入。这是微软收购动视暴雪后最具标志性的IP跨工作室调配，标志着Xbox第一方开发体系从343 Industries时代正式进入动视主导时代。" }
    ]
  },
  categories: [
    { id: "all", name: "全部资讯", icon: "🔥", desc: "汇总今日游戏开发全生态情报" },
    { id: "engine", name: "引擎前沿", icon: "🔧", desc: "Unity / 团结引擎 / 虚幻引擎 / Godot / 渲染技术" },
    { id: "industry", name: "行业热点", icon: "📰", desc: "大厂动向 / 财报 / 投融资 / 市场分析" },
    { id: "games", name: "热门游戏", icon: "🎮", desc: "新作发售 / 展会发布 / 热门追踪" },
    { id: "opensource", name: "开源宝库", icon: "⭐", desc: "GitHub 精选开源库 / 工具链 / 引擎框架" },
    { id: "tutorials", name: "实战教程", icon: "📚", desc: "DOTS / C# / 性能优化 / 架构设计" },
    { id: "ai", name: "AI前沿", icon: "🤖", desc: "AI NPC / 智能体 / 生成式AI / 大模型工具" }
  ],
  items: [
    { id: "xbox-pc-remote-unity", category: "engine", subcategory: "Unity工具链", title: "Xbox PC Remote Tools正式集成Unity 6.5：编辑器内一键远程构建部署到Windows设备", summary: "微软9月21日宣布Xbox PC Remote Tools现已内置于Unity 6.5，开发者可直接在Unity编辑器中对远程Windows设备进行一键构建、部署和迭代，无需生成Visual Studio项目。支持安全配对、增量部署、远程调试和文件管理，覆盖手持设备、桌面和测试机。", source: "Microsoft Developer / Microsoft Learn", date: "2026-09-21", url: "https://developer.microsoft.com/en-us/games/articles/2026/09/xbox-pc-remote-tools-are-now-available-in-unity/", image: "", badge: "Unity 6.5集成", badgeType: "engine", readTime: "3 分钟", hotScore: 82, tags: ["Unity", "Xbox PC Remote Tools", "远程部署", "Windows", "GDK" ], content: [{ title: "工具要点", type: "list", items: ["Unity 6.5内置支持；", "编辑器内一键远程构建部署；", "无需Visual Studio项目；", "安全PIN配对+增量部署；", "覆盖手持/桌面/测试机。"] }, { title: "摘要速读", type: "text", text: "Xbox PC Remote Tools集成Unity 6.5，编辑器内一键远程构建部署到Windows设备，无需VS项目。" }] },
    { id: "shinobi-switch2-launch", category: "games", subcategory: "Switch 2", title: "SHINOBI: Art of Vengeance今日登陆Switch 2：掌机模式更高分辨率", summary: "SEGA与Lizardcube开发的《SHINOBI: Art of Vengeance》于9月24日正式登陆Nintendo Switch 2，支持数字版和实体版。Switch 2版本在掌机模式下提供更高分辨率，画面如武士刀刀刃般锐利。支持从Switch版存档转移到Switch 2版。豪华版包含SEGA反派关卡DLC。", source: "SEGA / Gematsu", date: "2026-09-24", url: "https://www.gematsu.com/2026/06/shinobi-art-of-vengeance-coming-to-switch-2-on-september-24", image: "", badge: "今日Switch 2", badgeType: "game", readTime: "2 分钟", hotScore: 80, tags: ["SHINOBI", "SEGA", "Switch 2", "Lizardcube", "2D动作" ], content: [{ title: "发售信息", type: "list", items: ["9月24日Switch 2发售；", "数字版+实体版；", "掌机模式更高分辨率；", "Switch存档可转移；", "豪华版含SEGA反派关卡DLC。"] }, { title: "摘要速读", type: "text", text: "SHINOBI: Art of Vengeance今日登陆Switch 2，掌机模式更高分辨率，支持存档转移。" }] },
    { id: "fortnite-ai-npc-tool", category: "ai", subcategory: "Epic AI", title: "Fortnite推出AI驱动NPC定制工具：Epic进军生成式AI角色创作", summary: "Epic Games在Fortnite中推出AI驱动的NPC定制工具，允许创作者用自然语言描述生成自定义NPC角色，包括行为、对话和外观。这是Epic将生成式AI深度集成到游戏创作工具链的重要一步，标志着UEFN和Fortnite生态向AI辅助创作迈进。", source: "AI D-A-M-N / Summer Origin Tech", date: "2026-09-20", url: "https://ai-damn.com/fortnite-unveils-ai-powered-npc-customization-tool-1749081569736", image: "", badge: "AI NPC定制", badgeType: "ai", readTime: "2 分钟", hotScore: 78, tags: ["Fortnite", "Epic Games", "AI NPC", "生成式AI", "UEFN" ], content: [{ title: "工具要点", type: "list", items: ["自然语言生成自定义NPC；", "行为/对话/外观全定制；", "Epic生成式AI集成；", "UEFN生态AI辅助创作。"] }, { title: "摘要速读", type: "text", text: "Fortnite推出AI驱动NPC定制工具，Epic进军生成式AI角色创作，自然语言生成NPC。" }] },
    { id: "omnicore-ai-unity", category: "ai", subcategory: "Unity AI", title: "OmniCore AI插件登陆Unity：AI对话/语音/视觉/游戏状态解析全功能", summary: "OmniCore AI正式发布Unity插件，与Godot版功能完全一致。支持AI对话（NPC实时角色回应）、语音到语音（玩家麦克风输入NPC语音回应）、文本转语音、语音转文本、AI视觉（发送游戏状态获取神经网络决策）和游戏状态解析（AI读取世界状态）。", source: "OmniCore AI itch.io", date: "2026-09-17", url: "https://ahadprogamer.itch.io/omnicoreai/devlog/1580470/devlog-4-omnicore-ai-is-now-available-for-unity", image: "", badge: "Unity AI插件", badgeType: "ai", readTime: "2 分钟", hotScore: 74, tags: ["OmniCore AI", "Unity", "AI NPC", "语音", "游戏状态解析" ], content: [{ title: "插件功能", type: "list", items: ["AI对话NPC实时回应；", "语音到语音交互；", "TTS/STT支持；", "AI视觉游戏状态决策；", "与Godot版功能一致。"] }, { title: "摘要速读", type: "text", text: "OmniCore AI插件登陆Unity，AI对话/语音/视觉/游戏状态解析全功能，与Godot版一致。" }] },
    { id: "xbox-reset-three-quarters", category: "industry", subcategory: "Xbox重组", title: "Xbox内部备忘录：自7月以来重组已完成约四分之三，268人裁员属计划一部分", summary: "Xbox首席内容官Matt Booty在9月22日内部备忘录中披露，自7月以来的工作室剥离和裁员行动已完成约四分之三。本次268人裁员属于此前宣布的重组计划的一部分。备忘录确认Halo Studios将继续支持光环社区，但下一款正传由动视开发。", source: "Xbox Wire / 抖音内部邮件", date: "2026-09-22", url: "https://news.xbox.com/en-us/2026/09/22/continuing-our-reset/", image: "", badge: "重组进度75%", badgeType: "business", readTime: "2 分钟", hotScore: 76, tags: ["Xbox", "Matt Booty", "重组", "裁员", "内部备忘录" ], content: [{ title: "重组进度", type: "list", items: ["7月以来完成约四分之三；", "268人裁员属计划一部分；", "Halo Studios继续社区支持；", "下一款正传动视开发；", "减少业务部门数量整合团队。"] }, { title: "摘要速读", type: "text", text: "Xbox内部备忘录披露重组已完成约四分之三，268人裁员属计划一部分，Halo Studios继续社区支持。" }] },
    { id: "cod-studios-affected", category: "industry", subcategory: "Xbox重组", title: "COD系列受裁员影响工作室：Raven Software和Treyarch均在列", summary: "本次Xbox裁员中，《使命召唤》系列的Raven Software和Treyarch工作室均受到影响。动视将扩大业务范围涵盖World's Edge和Rare工作室。双倍经验活动将于9月26日周六凌晨1点开启。动视强调光环开发团队独立于COD现有开发计划。", source: "抖音 / GameLuster", date: "2026-09-23", url: "https://gameluster.com/next-halo-game-activision/", image: "", badge: "COD受影响", badgeType: "business", readTime: "1 分钟", hotScore: 70, tags: ["Raven", "Treyarch", "COD", "动视", "裁员" ], content: [{ title: "影响信息", type: "list", items: ["Raven和Treyarch受裁员影响；", "动视扩大范围含World's Edge和Rare；", "光环团队独立于COD计划；", "9/26双倍经验活动。"] }, { title: "摘要速读", type: "text", text: "COD系列Raven和Treyarch均受裁员影响，动视扩大范围含World's Edge和Rare。" }] },
    { id: "kingdom-rush-6", category: "games", subcategory: "塔防", title: "Kingdom Rush 6: Genesis TD今日PC发售：经典塔防系列正统续作", summary: "Ironhide Game Studio开发的《Kingdom Rush 6: Genesis TD》于9月24日在PC发售。这是经典塔防系列的第六部正统续作，玩家需要建造防御塔、指挥英雄抵御敌人进攻。延续系列标志性的手绘风格和策略深度。", source: "Instant Gaming News / Ironhide", date: "2026-09-24", url: "https://news.instant-gaming.com/en/articles/22006-this-week-s-releases-from-september-21-to-27-2026", image: "", badge: "今日发售", badgeType: "game", readTime: "1 分钟", hotScore: 66, tags: ["Kingdom Rush", "塔防", "Ironhide", "PC", "策略" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日PC发售；", "Kingdom Rush系列第六部；", "建造防御塔+指挥英雄；", "手绘风格+策略深度。"] }, { title: "摘要速读", type: "text", text: "Kingdom Rush 6: Genesis TD今日PC发售，经典塔防系列正统续作。" }] },
    { id: "qliphah-providence", category: "games", subcategory: "动作RPG", title: "Qliphah in Providence's Shadow今日发售：黑暗幻想动作RPG", summary: "Qliphah in Providence's Shadow于9月24日发售，登陆多平台。这是一款黑暗幻想风格的动作RPG游戏，玩家在 Providence 的阴影中探索战斗。游戏融合了动作战斗与RPG成长要素。", source: "Checkpoint Gaming", date: "2026-09-24", url: "https://checkpointgaming.net/features/2026/09/coming-out-in-gaming-this-week-september-21-2026/", image: "", badge: "今日发售", badgeType: "game", readTime: "1 分钟", hotScore: 64, tags: ["Qliphah", "动作RPG", "黑暗幻想", "多平台" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日发售；", "黑暗幻想动作RPG；", "动作战斗+RPG成长；", "多平台登陆。"] }, { title: "摘要速读", type: "text", text: "Qliphah in Providence's Shadow今日发售，黑暗幻想动作RPG。" }] },
    { id: "sin-reloaded", category: "games", subcategory: "重制版", title: "Sin: Reloaded今日全平台发售：经典FPS重制版登陆PS5/Xbox/Switch/PC", summary: "Sin: Reloaded于9月24日全平台发售，登陆PS5、Xbox Series X/S、Switch 2、PS4、Xbox One、Switch和PC。这是经典FPS游戏《Sin》的重制版，升级了画面和游戏性，同时保留原作的灵魂。", source: "Game Informer", date: "2026-09-24", url: "https://gameinformer.com/this-week", image: "", badge: "今日全平台", badgeType: "game", readTime: "1 分钟", hotScore: 68, tags: ["Sin", "重制版", "FPS", "全平台", "Nightdive" ], content: [{ title: "发售信息", type: "list", items: ["9月24日全平台发售；", "PS5/Xbox/Switch 2/PC等；", "经典FPS重制版；", "画面升级+保留原作灵魂。"] }, { title: "摘要速读", type: "text", text: "Sin: Reloaded今日全平台发售，经典FPS重制版登陆PS5/Xbox/Switch/PC。" }] },
    { id: "echoes-teradea", category: "games", subcategory: "JRPG", title: "Echoes of Teradea今日发售：日式RPG新作", summary: "Echoes of Teradea于9月24日发售。这是一款日式RPG新作，玩家在Teradea世界中展开冒险。游戏获得91分评价，被认为是近期值得关注的JRPG作品。", source: "NoobFeed", date: "2026-09-24", url: "https://www.noobfeed.com/games/filter?releasetype=release-desc#", image: "", badge: "今日发售", badgeType: "game", readTime: "1 分钟", hotScore: 62, tags: ["Echoes of Teradea", "JRPG", "日式RPG", "冒险" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日发售；", "日式RPG新作；", "Teradea世界冒险；", "91分评价。"] }, { title: "摘要速读", type: "text", text: "Echoes of Teradea今日发售，日式RPG新作，获91分评价。" }] },
    { id: "valor-mortis", category: "games", subcategory: "恐怖", title: "Valor Mortis今日发售：恐怖生存新作", summary: "Valor Mortis于9月24日发售。这是一款恐怖生存类游戏，玩家在危险环境中求生。作为本周恐怖游戏阵容的一部分，与Silent Hill: Townfall同期发售。", source: "NoobFeed", date: "2026-09-24", url: "https://www.noobfeed.com/games/filter?releasetype=release-desc#", image: "", badge: "今日发售", badgeType: "game", readTime: "1 分钟", hotScore: 60, tags: ["Valor Mortis", "恐怖", "生存", "多平台" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日发售；", "恐怖生存类；", "危险环境求生；", "与Silent Hill同期。"] }, { title: "摘要速读", type: "text", text: "Valor Mortis今日发售，恐怖生存新作，与Silent Hill: Townfall同期。" }] },
    { id: "gobble-release", category: "games", subcategory: "独立游戏", title: "GOBBLE今日发售：日本独立游戏新作", summary: "GOBBLE于9月24日发售，与Silent Hill: Townfall同日作为日本游戏发售阵容的一部分。这是一款独立游戏作品，具体玩法细节待确认。", source: "Gaming Ideology", date: "2026-09-24", url: "https://www.gamingideology.com/japanese-game-releases-silent-hill-townfall-and-gobble-arrive-september-24/", image: "", badge: "今日发售", badgeType: "game", readTime: "1 分钟", hotScore: 58, tags: ["GOBBLE", "独立游戏", "日本游戏", "多平台" ], content: [{ title: "发售信息", type: "list", items: ["9月24日发售；", "日本独立游戏；", "与Silent Hill同日发售。"] }, { title: "摘要速读", type: "text", text: "GOBBLE今日发售，日本独立游戏新作，与Silent Hill: Townfall同日。" }] },
    { id: "farming-camp-xbox", category: "games", subcategory: "模拟经营", title: "Farming Camp今日Xbox发售：温馨单人农场管理模拟，支持Xbox Play Anywhere", summary: "Farming Camp于9月24日登陆Xbox，优化支持Xbox Series X|S和Xbox Play Anywhere。这是一款温馨的单人农场管理模拟游戏，玩家经营自己的农场，体验宁静的乡村生活。由Soedesco发行。", source: "Gamer Fridge / Soedesco", date: "2026-09-24", url: "https://gamerfridge.com/2026/09/18/next-week-on-xbox-new-games-for-september-21-to-25/", image: "", badge: "今日Xbox", badgeType: "game", readTime: "1 分钟", hotScore: 60, tags: ["Farming Camp", "模拟经营", "Xbox", "Soedesco", "农场" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日Xbox发售；", "温馨单人农场管理；", "Xbox Play Anywhere支持；", "Soedesco发行。"] }, { title: "摘要速读", type: "text", text: "Farming Camp今日Xbox发售，温馨单人农场管理模拟，支持Xbox Play Anywhere。" }] },
    { id: "2048-battles-sylvan", category: "games", subcategory: "益智", title: "2048 Battles - Sylvan Sirens今日Xbox发售：森林女巫主题2048益智", summary: "2048 Battles - Sylvan Sirens于9月24日登陆Xbox，优化支持Xbox Series X|S。游戏为经典2048益智公式加入森林女巫和精灵女王主题，每个角色掌握自然魔法和特殊才能，为经典玩法增添奇幻色彩。", source: "Xbox Wire", date: "2026-09-24", url: "https://news.xbox.com/pt-br/2026/09/18/proxima-semana-em-xbox-novos-jogos-de-21-a-25-de-setembro/", image: "", badge: "今日Xbox", badgeType: "game", readTime: "1 分钟", hotScore: 56, tags: ["2048 Battles", "益智", "Xbox", "奇幻", "Sylvan Sirens" ], content: [{ title: "游戏信息", type: "list", items: ["9月24日Xbox发售；", "2048益智+森林女巫主题；", "角色掌握自然魔法；", "Xbox Series X|S优化。"] }, { title: "摘要速读", type: "text", text: "2048 Battles - Sylvan Sirens今日Xbox发售，森林女巫主题2048益智游戏。" }] },
    { id: "well-dweller-gamepass", category: "games", subcategory: "Game Pass", title: "Well Dweller登陆Xbox Game Pass：黑暗童话冒险，Crypt Custian和Islets开发者新作", summary: "Well Dweller于本周登陆Xbox Game Pass，这是一款黑暗童话冒险游戏，来自Crypt Custian和Islets的创作者。玩家在黑暗童话世界中探索冒险，游戏直接通过Game Pass提供，首日即可游玩。", source: "TechnoSports", date: "2026-09-24", url: "https://technosports.co.in/new-xbox-games-this-week-sept-21-25/?amp=1", image: "", badge: "Game Pass首日", badgeType: "game", readTime: "1 分钟", hotScore: 66, tags: ["Well Dweller", "Game Pass", "黑暗童话", "冒险", "独立" ], content: [{ title: "游戏信息", type: "list", items: ["本周登陆Game Pass；", "黑暗童话冒险；", "Crypt Custian和Islets开发者；", "首日即可游玩。"] }, { title: "摘要速读", type: "text", text: "Well Dweller登陆Xbox Game Pass，黑暗童话冒险，来自Crypt Custian和Islets创作者。" }] },
    { id: "godot-cpu-render-opt", category: "tutorials", subcategory: "Godot渲染", title: "Godot官方分享CPU端渲染代码优化实践：如何系统性优化渲染性能", summary: "Godot引擎官方于9月15日发布技术文章《Optimizing CPU-side Rendering Code》，详细分享了Godot团队如何系统性地优化CPU端渲染代码。文章涵盖了性能分析方法论、热点识别、缓存优化和多线程渲染等实践经验，对使用Godot的开发者具有直接参考价值。", source: "Godot Engine Blog", date: "2026-09-15", url: "https://godotengine.org/#:~:text=Your", image: "", badge: "渲染优化实战", badgeType: "engine", readTime: "3 分钟", hotScore: 72, tags: ["Godot", "CPU渲染", "性能优化", "多线程", "技术文章" ], content: [{ title: "优化要点", type: "list", items: ["系统性CPU端渲染优化；", "性能分析方法论；", "热点识别+缓存优化；", "多线程渲染实践；", "Godot 4.8开发中应用。"] }, { title: "摘要速读", type: "text", text: "Godot官方分享CPU端渲染代码优化实践，涵盖性能分析、热点识别、缓存优化和多线程渲染。" }] },
    { id: "unity-epic-fortnite-integration", category: "industry", subcategory: "引擎合作", title: "Unity与Epic Games合作推进Unity游戏登陆Fortnite：集成持续开发中，预计2027年EA", summary: "Unity与Epic Games的技术合作持续推进，目标是让Unity制作的游戏能够登陆Fortnite生态。根据9月14日核实的官方信息，集成仍在开发中，时间表、技术要求、发布规则和商业条件可能在2027年预计的抢先体验之前发生变化。这是两大引擎厂商史无前例的合作。", source: "Noticias Negocio Tec / Unity", date: "2026-09-14", url: "https://noticias.negocio.tec.br/m/unity-e-epic-games-unem-tecnologias-para-levar-jogos-feitos-na-unity-ao-fortnite/", image: "", badge: "引擎史无前例合作", badgeType: "business", readTime: "2 分钟", hotScore: 74, tags: ["Unity", "Epic Games", "Fortnite", "引擎合作", "2027 EA" ], content: [{ title: "合作要点", type: "list", items: ["Unity游戏登陆Fortnite生态；", "集成持续开发中；", "预计2027年抢先体验；", "技术要求和商业条件可能变化；", "两大引擎史无前例合作。"] }, { title: "摘要速读", type: "text", text: "Unity与Epic合作推进Unity游戏登陆Fortnite，集成持续开发中，预计2027年EA。" }] },
    { id: "crimson-desert-engine", category: "industry", subcategory: "自研引擎", title: "Pearl Abyss解释《红色沙漠》为何用自研引擎：掌握主动权比省事更重要", summary: "Pearl Abyss首席工程师金镇焕和引擎图形部门高级负责人尹振浩在科隆游戏展期间接受采访时表示，既然《黑色沙漠》的引擎是内部自研而来，新项目《红色沙漠》再转而选用第三方商用引擎反而不合理。他们认为商用引擎虽优秀，但自研引擎能掌握完全主动权，避免受第三方技术路线制约。", source: "IT之家 / Mein MMO", date: "2026-09-21", url: "http://m.toutiao.com/group/7687919186772771330/", image: "", badge: "自研引擎哲学", badgeType: "business", readTime: "2 分钟", hotScore: 70, tags: ["Pearl Abyss", "红色沙漠", "自研引擎", "黑色沙漠", "科隆展" ], content: [{ title: "引擎选择", type: "list", items: ["红色沙漠使用自研引擎；", "黑色沙漠引擎延续；", "掌握主动权比省事重要；", "避免第三方技术路线制约；", "Pearl Abyss引擎团队。"] }, { title: "摘要速读", type: "text", text: "Pearl Abyss解释红色沙漠用自研引擎，掌握主动权比省事更重要，避免第三方技术制约。" }] },
    { id: "niagara-examples-pack", category: "engine", subcategory: "UE5特效", title: "Epic发布Niagara Examples Pack：50+即用型Niagara特效系统，UE5.7直接可用", summary: "Epic Games发布Niagara Examples Pack，包含超过50个即用型Niagara粒子特效系统，可直接在Unreal Engine 5.7项目中使用。涵盖爆炸、弹坑、轨迹、火花、火焰、烟雾以及玩家和武器增益/减益效果等，为开发者提供高质量的特效参考和直接可用的资源。", source: "Epic Games / Unreal Engine", date: "2026-09-20", url: "https://dev.epicgames.com/indies/news?lang=de", image: "", badge: "Niagara特效包", badgeType: "engine", readTime: "2 分钟", hotScore: 72, tags: ["UE5", "Niagara", "特效", "Epic Games", "UE5.7" ], content: [{ title: "特效包内容", type: "list", items: ["50+即用型Niagara系统；", "UE5.7直接可用；", "爆炸/弹坑/轨迹/火花；", "火焰/烟雾效果；", "玩家/武器增益减益。"] }, { title: "摘要速读", type: "text", text: "Epic发布Niagara Examples Pack，50+即用型特效系统，UE5.7直接可用，涵盖爆炸/火焰/烟雾等。" }] },
    { id: "unity-2026-dev-report", category: "industry", subcategory: "行业报告", title: "Unity发布2026游戏开发报告：五大趋势揭示工作室如何构建韧性可持续未来", summary: "Unity发布《2026 Unity Game Development Report》，揭示了五大趋势，展示工作室如何在快速变化的视频游戏行业中构建韧性和可持续的未来。报告基于行业数据和开发者调研，为游戏开发者和工作室提供战略参考。", source: "Unity", date: "2026-09-23", url: "https://unity.com/", image: "", badge: "行业报告", badgeType: "business", readTime: "2 分钟", hotScore: 68, tags: ["Unity", "行业报告", "2026", "游戏开发趋势", "可持续" ], content: [{ title: "报告要点", type: "list", items: ["2026游戏开发报告发布；", "五大趋势揭示；", "韧性可持续未来；", "行业数据+开发者调研；", "战略参考价值。"] }, { title: "摘要速读", type: "text", text: "Unity发布2026游戏开发报告，五大趋势揭示工作室如何构建韧性可持续未来。" }] },
    { id: "summer-engine-ai-npc", category: "ai", subcategory: "AI工具", title: "Summer Engine AI NPC Generator：自然语言描述直接生成可运行游戏NPC", summary: "Summer Engine推出AI NPC Generator，开发者用自然语言描述角色，AI直接将行为、对话、导航和模型构建到实际游戏项目中。与其他只生成性格描述或头像的工具不同，Summer Engine生成的NPC直接落地到真实游戏引擎中，无需手动接线。", source: "Summer Engine", date: "2026-09-14", url: "https://www.summerengine.com/ai-npc-generator", image: "", badge: "AI NPC生成器", badgeType: "ai", readTime: "2 分钟", hotScore: 70, tags: ["Summer Engine", "AI NPC", "自然语言", "游戏集成", "生成式AI" ], content: [{ title: "工具特点", type: "list", items: ["自然语言描述生成NPC；", "行为/对话/导航/模型全构建；", "直接落地到游戏引擎；", "无需手动接线；", "区别于只生成描述的工具。"] }, { title: "摘要速读", type: "text", text: "Summer Engine AI NPC Generator用自然语言直接生成可运行游戏NPC，行为/对话/导航全构建。" }] },
    { id: "ue-emea-developer-days", category: "industry", subcategory: "UE活动", title: "虚幻引擎EMEA开发者日即将举行：欧洲中东非洲多城市汇聚UE开发者", summary: "Epic Games宣布虚幻引擎EMEA（欧洲、中东及非洲）开发者日即将在多个城市举行，汇聚虚幻引擎开发者共同学习、交流并分享创意。这是UE社区的重要区域性活动，为开发者提供与Epic工程师和同行交流的机会。", source: "Unreal Engine", date: "2026-09-03", url: "https://www.unrealengine.com/feed?groupid=28.218.81807.7598.81814&pid=1194454", image: "", badge: "UE开发者日", badgeType: "event", readTime: "1 分钟", hotScore: 62, tags: ["Unreal Engine", "EMEA", "开发者日", "Epic Games", "社区活动" ], content: [{ title: "活动信息", type: "list", items: ["EMEA多城市举行；", "UE开发者汇聚；", "学习交流分享创意；", "与Epic工程师交流。"] }, { title: "摘要速读", type: "text", text: "虚幻引擎EMEA开发者日即将举行，欧洲中东非洲多城市汇聚UE开发者。" }] },
    { id: "shining-isle-ue5", category: "engine", subcategory: "UE5动画", title: "Shining Isle Productions全面转向UE5制作《翼飞传奇》：动画管线全引擎内完成", summary: "Shining Isle Productions将整个动画管线迁移到Unreal Engine，制作《The Wingfeather Saga》（翼飞传奇）。团队快速培训艺术家，在引擎内完成绑定和动画，实现更快的迭代和即时审查，从优秀到卓越的品质提升。这是UE5在动画剧集制作中的典型案例。", source: "Unreal Engine", date: "2026-06-24", url: "https://www.unrealengine.com/feed?categories=all&page=4", image: "", badge: "UE5动画管线", badgeType: "engine", readTime: "2 分钟", hotScore: 68, tags: ["UE5", "Shining Isle", "Wingfeather Saga", "动画", "管线迁移" ], content: [{ title: "管线要点", type: "list", items: ["整个动画管线迁移到UE5；", "引擎内绑定和动画；", "快速迭代+即时审查；", "动画剧集制作案例；", "品质从优秀到卓越。"] }, { title: "摘要速读", type: "text", text: "Shining Isle Productions全面转向UE5制作翼飞传奇，动画管线全引擎内完成，快速迭代。" }] },
    { id: "halo-studios-community", category: "industry", subcategory: "Xbox重组", title: "Halo Studios将继续支持光环社区：不再主导正传但保留社区运营职能", summary: "微软确认Halo Studios（前343 Industries）在裁员268人后将继续存在，专注于支持光环社区。虽然下一款光环正传由动视和Sledgehammer开发，但Halo Studios仍将负责社区互动、活动运营和系列维护。这标志着343时代的正式终结。", source: "Gadgets 360 / Xbox Wire", date: "2026-09-23", url: "https://www.gadgets360.com/games/news/xbox-layoffs-studio-restructuring-announced-next-halo-game-development-activision-12085212", image: "", badge: "343时代终结", badgeType: "business", readTime: "2 分钟", hotScore: 72, tags: ["Halo Studios", "343 Industries", "光环社区", "Xbox", "重组" ], content: [{ title: "职能调整", type: "list", items: ["Halo Studios继续存在；", "专注社区支持；", "不再主导正传开发；", "社区互动+活动运营；", "343时代正式终结。"] }, { title: "摘要速读", type: "text", text: "Halo Studios将继续支持光环社区，不再主导正传但保留社区运营职能，343时代终结。" }] },
    { id: "xbox-pc-remote-2609", category: "engine", subcategory: "Xbox工具链", title: "Xbox PC Remote Tools 2609版发布：远程迭代API+命令行工具+VS调试扩展", summary: "微软发布Xbox PC Remote Tools 2026年9月（2609）版本，包含Xbox PC远程迭代API、wdRemote命令行工具和Xbox PC远程调试器Visual Studio扩展。工具集支持安全配置、PIN配对、增量游戏部署、游戏生命周期管理和远程工具执行，覆盖局域网内的手持设备、桌面和测试机。", source: "Microsoft Learn", date: "2026-09-15", url: "https://learn.microsoft.com/en-us/gaming/gdk/docs/gdk-dev/pc-dev/tutorials/get-started-with-remote-devices/release-notes/rwd-release-notes-2609?view=gdk-2510", image: "", badge: "2609版发布", badgeType: "engine", readTime: "2 分钟", hotScore: 66, tags: ["Xbox PC Remote Tools", "GDK", "远程调试", "Visual Studio", "2609" ], content: [{ title: "工具组件", type: "list", items: ["远程迭代API；", "wdRemote命令行工具；", "VS调试扩展；", "安全PIN配对+增量部署；", "覆盖手持/桌面/测试机。"] }, { title: "摘要速读", type: "text", text: "Xbox PC Remote Tools 2609版发布，含远程迭代API+命令行工具+VS调试扩展，支持增量部署。" }] },
    { id: "state-of-unreal-2026-recap", category: "industry", subcategory: "UE活动", title: "State of Unreal 2026回顾：UE6愿景发布+UE5.8推出+开源版本控制Lore+UEFN生态壮大", summary: "State of Unreal 2026大会回顾：Epic分享了虚幻引擎6的愿景，发布了虚幻引擎5.8，推出了开源的下一代版本控制系统Lore，见证了UEFN日益壮大的开发者生态系统，同时预览了Epic游戏商城即将推出的改进。UE6将整合UE5的AAA能力与Fortnite中构建的下一代开发管线。", source: "Unreal Engine / launcher-website", date: "2026-06-17", url: "https://www.unrealengine.com/news/state-of-unreal-2026-top-news-from-the-show", image: "", badge: "State of Unreal", badgeType: "event", readTime: "3 分钟", hotScore: 74, tags: ["State of Unreal", "UE6", "UE5.8", "Lore", "UEFN" ], content: [{ title: "大会要点", type: "list", items: ["UE6愿景发布；", "UE5.8推出；", "开源版本控制Lore；", "UEFN生态壮大；", "Epic商城改进预览。"] }, { title: "摘要速读", type: "text", text: "State of Unreal 2026回顾：UE6愿景+UE5.8+开源Lore+UEFN生态，UE6整合AAA能力与Fortnite管线。" }] }
  ]
};
